tarball: native src
native:
	PRECOMPILED_HEADER_DIR=/home/fox/tmp/finmag-pch make -C native
src:
	FINMAGDIST_DEST_TARBALL=finmag.1.tar make -C src libs cp bundle
clean:
	make -C src cleanall
	make -C native clean
	hg purge src
	hg purge native

.PHONY: native src
