"""Direct DOLFINx ``ThinFilmDemag`` port (Task 19 + SR1 P5.2 minimal-diff
transcription).

This file now lives at its master path
``src/finmag/energies/thin_film_demag_test.py`` (formerly
``src/finmag/tests/test_thin_film_demag_dolfinx.py``), so
``git diff b5015c5a..HEAD -- src/finmag/energies/thin_film_demag_test.py``
shows the port diff directly.

This file has two clearly separated parts:

1. A MINIMAL-DIFF transcription of the master unit tests from
   ``src/finmag/energies/thin_film_demag_test.py`` (git ``b5015c5a``).
   Function names, ordering, assertion structure and TOLERANCES are kept
   identical to master; the only differences are (a) dolfin->dolfinx API
   changes (each annotated inline), (b) the py2->py3 ``print`` conversion,
   and (c) explanatory comments. ``ThinFilmDemag`` is legacy's analytic
   thin-film demagnetising approximation (``Hi = -strength_i * m_i`` for a
   single chosen axis ``i``, ``strength`` defaulting to a box-averaged
   ``Ms``) -- the last legacy-tested energy class still importing
   ``dolfin`` at module scope before this port.

2. The sophisticated NEW-under-DOLFINx tests (construction/setup
   validation, the "recomputed fresh on every call" contract, the explicit
   ``field_strength`` branch, coordinate-ordered legacy oracle fixture
   comparisons, ``Simulation.add()`` integration), which have no master
   ancestor. They live below the ``NEW under DOLFINx`` banner and are
   unchanged.

The NEW tests validate the ported ``finmag.energies.thin_film_demag.ThinFilmDemag``
against:

- construction/setup validation consistent with every other ported
  interaction (Field type checks, CG1 requirement, mesh-matching, invalid
  ``direction``);
- the "recomputed fresh on every call" contract (not cached at ``setup``
  time, unlike the documented ``DiscreteTimeZeeman`` legacy defect);
- the explicit ``field_strength`` branch (bypasses the ``Ms``-average
  entirely);
- coordinate-ordered legacy oracle fixture comparisons (both the
  ``field_strength=None``/varying-``Ms`` branch and the explicit-
  ``field_strength`` branch) against
  ``src/finmag/tests/fixtures/thin_film_demag_oracle.json``, regenerated by
  ``src/finmag/tests/fixtures/gen_thin_film_demag_oracle.py``;
- ``Simulation.add()`` integration (legacy never wired this into
  ``sim_with``; it is only ever added directly, exactly as ported here).

[Claude Sonnet 5]
"""

import json
import os

import numpy as np
import pytest
from dolfinx import fem, mesh
from mpi4py import MPI

from finmag.energies import ThinFilmDemag, Demag
from finmag.field import Field
from finmag.sim.sim import Simulation

# Master's module-level constant was named ``Ms``; renamed here to avoid
# clashing with the many local ``Ms`` Field variables used throughout this
# file (both below and in the NEW section).
Ms_CONST = 8.6e5


# ==========================================================================
# MINIMAL-DIFF transcription of master thin_film_demag_test.py (git b5015c5a).
# dolfin->dolfinx changes are annotated inline; tolerances are master's,
# each passing verbatim under DOLFINx.
# ==========================================================================

def test_interaction_accepts_name():
    """
    Check that the interaction accepts a 'name' argument and has a 'name' attribute.
    """
    demag = ThinFilmDemag()
    assert hasattr(demag, 'name')


def compare_with_demag_from_initial_m(H_gen, m_init, atol=0, rtol=0):
    # df.UnitCubeMesh(2, 2, 2) -> dolfinx mesh.create_unit_cube;
    # Sim(...) -> Simulation(...) (same constructor shape: mesh, Ms, unit_length=).
    domain = mesh.create_unit_cube(MPI.COMM_WORLD, 2, 2, 2)
    sim = Simulation(domain, Ms_CONST, unit_length=1e-9)
    sim.set_m(m_init)

    demag = ThinFilmDemag()
    sim.add(demag)
    H_computed = demag.compute_field()
    H_expected = H_gen(sim.m)

    diff = np.abs(H_computed - H_expected)
    print("Expected, with shape {}:\n".format(H_expected.shape), H_expected)  # py2 print stmt -> py3 print()
    print("Got, with shape {}:\n".format(H_computed.shape), H_computed)
    print("Difference:\n", diff)
    assert np.allclose(H_computed, H_expected, atol=atol, rtol=rtol)


def test_zero_thin_film_demag():
    compare_with_demag_from_initial_m(
        lambda m: np.zeros(m.shape), (1, 0, 0), atol=1e-14)
    compare_with_demag_from_initial_m(
        lambda m: np.zeros(m.shape), (1, 1, 0), atol=1e-14)


def test_thin_film_demag():
    compare_with_demag_from_initial_m(lambda m: -Ms_CONST * m, (0, 0, 1), rtol=1e-14)


@pytest.mark.slow
def test_thin_film_demag_against_real_demag():
    # df.BoxMesh(df.Point(0,0,0), df.Point(500e-9,500e-9,1e-9), 50, 50, 1)
    # -> dolfinx mesh.create_box with an explicit tetrahedron cell type.
    domain = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (500e-9, 500e-9, 1e-9)],
        [50, 50, 1], mesh.CellType.tetrahedron)
    sim = Simulation(domain, Ms_CONST)
    sim.set_m((0, 0, 1))

    tfdemag = ThinFilmDemag()
    sim.add(tfdemag)
    # .view() dropped: dolfinx compute_field() already returns a fresh array.
    H_tfdemag = tfdemag.compute_field().reshape((3, -1)).mean(1)
    demag = Demag()
    sim.add(demag)
    H_demag = demag.compute_field().reshape((3, -1)).mean(1)

    diff = np.abs(H_tfdemag - H_demag) / Ms_CONST
    print("Standard Demag:\n", H_demag)
    print("ThinFilmDemag:\n", H_tfdemag)
    print("Difference relative to Ms:\n", diff)
    assert np.allclose(H_tfdemag, H_demag, atol=0.05 * Ms_CONST)  # 5% of Ms

    sim.set_m((1, 0, 0))
    H_tfdemag = tfdemag.compute_field().reshape((3, -1)).mean(1)
    H_demag = demag.compute_field().reshape((3, -1)).mean(1)

    print("Running again, changed m in the meantime.")
    diff = np.abs(H_tfdemag - H_demag) / Ms_CONST
    print("Standard Demag:\n", H_demag)
    print("ThinFilmDemag:\n", H_tfdemag)
    print("Difference relative to Ms:\n", diff)
    assert np.allclose(H_tfdemag, H_demag, atol=0.005 * Ms_CONST)  # 0.5% of Ms


# ==========================================================================
# ===== NEW under DOLFINx (no master ancestor) =============================
# ==========================================================================
# Construction/setup validation, the recompute-fresh contract, the explicit
# field_strength branch, coordinate-ordered legacy oracle-fixture
# comparisons, and Simulation integration below have no ancestor in master
# thin_film_demag_test.py.

def _cube(cells=2):
    return mesh.create_unit_cube(MPI.COMM_WORLD, cells, cells, cells)


def _fields(domain, m_value, Ms=Ms_CONST):
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    return Field(S3, m_value, name="m"), Field(DG, Ms, name="Ms")


# --------------------------------------------------------------------------
# import boundary / construction
# --------------------------------------------------------------------------

def test_thin_film_demag_export_does_not_load_legacy_dolfin():
    import sys

    assert ThinFilmDemag.__module__ == "finmag.energies.thin_film_demag"
    assert "dolfin" not in sys.modules


def test_invalid_direction_raises_value_error():
    with pytest.raises(ValueError, match="direction"):
        ThinFilmDemag(direction="w")


def test_requires_three_component_m_field():
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("Lagrange", 1))
    m = Field(scalar_space, 1.0)
    Ms = Field(fem.functionspace(domain, ("DG", 0)), Ms_CONST)
    with pytest.raises(ValueError, match="three-component"):
        ThinFilmDemag().setup(m, Ms, 1e-9)


def test_requires_field_instances():
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0))
    with pytest.raises(TypeError, match="finmag.Field"):
        ThinFilmDemag().setup(m.as_array(), Ms, 1e-9)
    with pytest.raises(TypeError, match="finmag.Field"):
        ThinFilmDemag().setup(m, Ms.as_array(), 1e-9)


def test_requires_matching_mesh():
    domain_a = _cube()
    domain_b = _cube(cells=3)
    m, _ = _fields(domain_a, (0.0, 0.0, 1.0))
    _, Ms = _fields(domain_b, (0.0, 0.0, 1.0))
    with pytest.raises(ValueError, match="same mesh"):
        ThinFilmDemag().setup(m, Ms, 1e-9)


# --------------------------------------------------------------------------
# recompute-fresh contract
# --------------------------------------------------------------------------

def test_compute_field_is_recomputed_fresh_every_call():
    """Not a legacy-file transcription, but a direct pin of the "not cached"
    contract legacy's own ``compute_field`` relies on (it always reads
    ``self.m.get_numpy_array_debug()`` fresh) -- worth pinning explicitly
    given the documented ``DiscreteTimeZeeman`` legacy caching defect
    elsewhere in this port (see ``zeeman.py``)."""
    domain = _cube()
    m, Ms = _fields(domain, (1.0, 0.0, 0.0))
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)

    first = demag.compute_field()
    np.testing.assert_allclose(first, np.zeros_like(first), atol=1e-14)

    m.set((0.0, 0.0, 1.0))
    second = demag.compute_field()
    # compute_field() is component-blocked (Task 31); compare against the
    # blocked m (here H == -Ms * m because m lies purely along the z direction).
    expected = -Ms_CONST * m.get_ordered_numpy_array_xxx()
    np.testing.assert_allclose(second, expected, rtol=1e-14)


# --------------------------------------------------------------------------
# field_strength branches
# --------------------------------------------------------------------------

def test_explicit_field_strength_bypasses_ms_average():
    domain = _cube()
    m, Ms = _fields(domain, (1.0, 0.0, 0.0), Ms=1.0e6)
    demag = ThinFilmDemag(direction="x", field_strength=250.0)
    demag.setup(m, Ms, unit_length=1e-9)
    H = demag.compute_field().reshape((3, -1)).T
    expected = np.zeros_like(H)
    expected[:, 0] = -250.0 * 1.0
    np.testing.assert_allclose(H, expected, rtol=1e-14)


def test_default_field_strength_is_ms_box_average():
    """``field_strength=None`` (the default) recovers a uniform ``Ms``
    exactly via the box average, matching ``test_thin_film_demag`` above but
    asserting the intermediate ``strength`` explicitly."""
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0), Ms=Ms_CONST)
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)
    np.testing.assert_allclose(demag.strength, Ms_CONST, rtol=1e-10)


def test_compute_energy_is_the_legacy_literal_zero():
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0))
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)
    assert demag.compute_field() is not None  # sanity: setup succeeded
    assert demag.compute_energy() == 0


# --------------------------------------------------------------------------
# coordinate-ordered legacy oracle comparisons
# --------------------------------------------------------------------------

# Oracle fixtures live under ``src/finmag/tests/fixtures/``; this file now sits
# at its master path ``src/finmag/energies/thin_film_demag_test.py`` (formerly
# ``src/finmag/tests/test_thin_film_demag_dolfinx.py``), one directory up and
# across, hence the ``os.pardir`` hop.
_FIXTURE = os.path.join(
    os.path.dirname(__file__), os.pardir, "tests", "fixtures",
    "thin_film_demag_oracle.json")
ORACLE = json.load(open(_FIXTURE))
CASES = ORACLE["cases"]


def _quantity(case, name):
    for q in case["quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _scalar_quantity(case, name):
    for q in case["scalar_quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _oracle_box_mesh():
    extent = 0.7
    return mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (extent, extent, extent)],
        [3, 3, 3], mesh.CellType.tetrahedron)


def _oracle_m():
    def f(x):
        return np.vstack(
            (np.full(x.shape[1], 0.6), 0.8 * np.cos(2.0 * np.pi * x[0]),
             0.8 * np.sin(2.0 * np.pi * x[0]))
        )

    return f


def _oracle_ms():
    def f(x):
        return 800000.0 * (1.0 + 0.3 * x[0] / 0.7)

    return f


def _oracle_compare(case_name, direction, field_strength):
    case = CASES[case_name]
    domain = _oracle_box_mesh()
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    m = Field(S3, _oracle_m(), name="m")
    Ms = Field(DG, _oracle_ms(), name="Ms")

    demag = ThinFilmDemag(direction=direction, field_strength=field_strength)
    demag.setup(m, Ms, unit_length=1e-9)
    E = demag.compute_energy()
    # compute_field() is component-blocked (Task 31); per-node rows are
    # reshape((3, -1)).T in owned-vertex order, matching coords_and_values().
    H = demag.compute_field().reshape((3, -1)).T
    coords, _ = m.coords_and_values()
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    coords_s, H_s = coords[order], H[order]

    ref_coords = np.asarray(case["coordinates"]["values"])
    energy_q = _scalar_quantity(case, "energy")
    H_q = _quantity(case, "H_vertex")
    m_q = _quantity(case, "m_vertex")

    assert coords_s.shape == ref_coords.shape
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    m_coords, m_values = m.coords_and_values()
    m_order = np.lexsort((m_coords[:, 2], m_coords[:, 1], m_coords[:, 0]))
    np.testing.assert_allclose(
        m_values[m_order], np.asarray(m_q["values"]),
        atol=m_q["tolerances"]["absolute"], rtol=m_q["tolerances"]["relative"])

    e_tol = energy_q["tolerances"]
    np.testing.assert_allclose(
        float(E), energy_q["value"], atol=e_tol["absolute"], rtol=e_tol["relative"])
    H_tol = H_q["tolerances"]
    np.testing.assert_allclose(
        H_s, np.asarray(H_q["values"]), atol=H_tol["absolute"],
        rtol=H_tol["relative"])


def test_oracle_varying_ms_default_strength():
    _oracle_compare("varying_ms_default_strength", "z", None)


def test_oracle_explicit_strength_x_direction():
    _oracle_compare("explicit_strength_x_direction", "x", 5.0e5)


# --------------------------------------------------------------------------
# Simulation integration (legacy never wired ThinFilmDemag into sim_with;
# it is only ever added directly, exactly as ported here)
# --------------------------------------------------------------------------

def test_thin_film_demag_added_to_simulation_directly():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, Ms_CONST, unit_length=1e-9, name="thin_film_demag_direct")
    sim.set_m((0.0, 0.0, 1.0))
    sim.add(ThinFilmDemag())
    assert sim.has_interaction("ThinFilmDemag")
    assert sim.total_energy() == pytest.approx(0.0, abs=1e-25)
    interaction = sim.get_interaction("ThinFilmDemag")
    H = interaction.compute_field().reshape((3, -1)).T
    expected = np.zeros_like(H)
    expected[:, 2] = -Ms_CONST
    np.testing.assert_allclose(H, expected, rtol=1e-12)
