"""Direct DOLFINx cubic-anisotropy port (Task 14).

Validates the ported ``finmag.energies.cubic_anisotropy.CubicAnisotropy``
against:

- the legacy module's own analytic reference values (transcribed from
  ``finmag.energies.cubic_anisotropy_test.py::test_cubic_anisotropy_energy``:
  same ``K1``/``K2``/``K3``/``u1``/``u2`` constants, same uniform
  ``m = (0, 0, 1)``);
- cubic-symmetry easy/hard-axis energy ordering for the standard orthonormal
  crystallographic axes (``K1 > 0``): ``E([100]) == 0``,
  ``E([110]) - E([100]) == K1/4 * V``, ``E([111]) - E([100]) == K1/3 * V``
  (derived from the transcribed energy-density form itself, not assumed);
- the ``K2``/``K3`` contributions in isolation (the other two constants set
  to zero);
- axis-handling behavior transcribed exactly from the legacy class: ``u3 =
  u1 x u2``, and ``u1``/``u2`` are used *as given* -- neither renormalised
  nor checked for orthogonality (matching
  ``dev/dolfinx/prototype.py::cubic_anisotropy_energy``'s documented
  investigation and the legacy class's own non-unit,
  not-quite-orthogonal ``cubic_anisotropy_test.py`` axes);
- by-name deferral of spatially varying ``K1``/``K2``/``K3``/``u1``/``u2``;
- the ported legacy-default ``assemble=False`` *native analytic* effective
  field (``H = -1/(mu0 Ms) dE/dm``, a NumPy transcription of
  ``native/src/llg/energy.cc::compute_cubic_field``): matches a hand
  derivation to machine precision, matches per-term legacy native oracle
  fixtures (K1/K2/K3-only + all-nonzero), and the box-assemble field
  converges toward it under refinement -- including the K2 native-typo
  evidence (``energy.cc:116`` ``K2[2]`` index, dormant for constant K2);
- a coordinate-ordered legacy oracle fixture comparison (field + energy)
  against ``src/finmag/tests/fixtures/cubic_anisotropy_oracle.json``
  (assemble=True box field) and
  ``cubic_anisotropy_native_oracle.json`` (assemble=False native field),
  regenerated by their respective ``gen_*`` scripts;
- ``Simulation``/``sim.add(...)`` integration, including a dynamics effect
  for both the assemble=True and legacy-default assemble=False constructors.

[Claude Sonnet 5]; assemble=False native-field port [Claude Opus 4.8]
"""

import json
import os

import numpy as np
import pytest
from dolfinx import fem, mesh
from mpi4py import MPI

from finmag.energies import CubicAnisotropy
from finmag.field import Field
from finmag.sim.sim import Simulation

_FIXTURE = os.path.join(
    os.path.dirname(__file__), "fixtures", "cubic_anisotropy_oracle.json")
ORACLE = json.load(open(_FIXTURE))
CASE = ORACLE["cases"]["cubic_3d"]


def _cube(cells=2):
    return mesh.create_unit_cube(MPI.COMM_WORLD, cells, cells, cells)


def _fields(domain, m_value, Ms=8.0e5):
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    return Field(S3, m_value, name="m"), Field(DG, Ms, name="Ms")


def _domain_volume(domain):
    import ufl

    local = fem.assemble_scalar(fem.form(fem.Constant(domain, 1.0) * ufl.dx))
    return domain.comm.allreduce(local, op=MPI.SUM)


# ==========================================================================
# MINIMAL-DIFF transcription of master cubic_anisotropy_test.py (git b5015c5a).
# Function names, ordering, assertion structure and the TOLERANCE are kept
# identical to master; dolfin->dolfinx API changes are annotated inline, the
# py2->py3 ``print`` conversion is the only syntax change, and the measured
# DOLFINx value is recorded beside the (verbatim) tolerance.
# ==========================================================================

unit_length = 1e-9
Ms = 876626  # A/m

K1 = -8608726
K2 = -13744132
K3 = 1100269
u1 = (0, -0.7071, 0.7071)
u2 = (0,  0.7071, 0.7071)
u3 = (-1, 0, 0)  # perpendicular to u1 and u2


def compute_cubic_energy():
    m = (0, 0, 1)
    u1m = np.dot(u1, m)
    u2m = np.dot(u2, m)
    u3m = np.dot(u3, m)
    energy = K1 * \
        (u1m ** 2 * u2m ** 2 + u1m ** 2 * u3m ** 2 + u2m ** 2 * u3m ** 2)
    energy += K2 * (u1m ** 2 * u2m ** 2 * u3m ** 2)
    energy += K3 * \
        (u1m ** 4 * u2m ** 4 + u1m ** 4 * u3m ** 4 + u2m ** 4 * u3m ** 4)
    return energy


def test_cubic_anisotropy_energy():
    # df.BoxMesh(df.Point(0, 0, 0), df.Point(1, 1, 40), 1, 1, 40) ->
    # mesh.create_box(MPI.COMM_WORLD, [(0,0,0), (1,1,40)], [1,1,40], tetrahedron)
    domain = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (1.0, 1.0, 40.0)], [1, 1, 40],
        mesh.CellType.tetrahedron)
    # meshes.mesh_volume(mesh) -> no dolfinx equivalent helper exists; the
    # byte-identical cell-volume-assembly reimplementation used throughout
    # this port (_domain_volume, defined above) stands in for it.
    volume = _domain_volume(domain) * unit_length ** 3
    # df.VectorFunctionSpace(mesh, "Lagrange", 1) ->
    # fem.functionspace(domain, ("Lagrange", 1, (3,)))
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    # df.FunctionSpace(mesh, "Lagrange", 1) -> fem.functionspace(domain, ("Lagrange", 1))
    # (S1 is unused beyond construction in master too; kept for diff fidelity.)
    S1 = fem.functionspace(domain, ("Lagrange", 1))

    # m = Field(S3); m.set((0, 0, 1)) -> Field(S3, value) constructs and sets
    # in one call under DOLFINx.
    m = Field(S3, (0, 0, 1))

    # Ms_dg = Field(df.FunctionSpace(mesh, 'DG', 0), Ms) -> DG functionspace.
    Ms_dg = Field(fem.functionspace(domain, ("DG", 0)), Ms)

    ca = CubicAnisotropy(u1, u2, K1, K2, K3)
    ca.setup(m, Ms_dg, unit_length)

    energy = ca.compute_energy()
    # energy_expected = 8.3e-20  # oommf cubicEight_100pc.mif -> ErFe2.odt
    energy_expected = compute_cubic_energy() * volume
    # print "..." (py2) -> print("...") (py3)
    print("cubic anisotropy energy = {}, expected {}.".format(energy, energy_expected))

    rel_diff = abs(energy - energy_expected) / abs(energy_expected)
    # master tol 1e-10; measured DOLFINx rel_diff ~1e-15 (machine precision) -> passes verbatim
    assert rel_diff < 1e-10


# ===== NEW under DOLFINx (no master ancestor) =====
# Master's cubic_anisotropy_test.py has exactly one test function (transcribed
# above, verbatim); everything below is new coverage added during the DOLFINx
# port, validating axis handling, K2/K3 isolation, spatially varying
# parameters/axes, the assemble=False native-analytic field, legacy oracle
# fixtures, and Simulation integration.


# --------------------------------------------------------------------------
# import boundary
# --------------------------------------------------------------------------

def test_cubic_anisotropy_export_does_not_load_legacy_dolfin():
    import sys

    assert CubicAnisotropy.__module__ == "finmag.energies.cubic_anisotropy"
    assert "dolfin" not in sys.modules


def test_cubic_anisotropy_requires_three_component_field():
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("Lagrange", 1))
    m = Field(scalar_space, 1.0)
    Ms = Field(fem.functionspace(domain, ("DG", 0)), 8.0e5)
    with pytest.raises(ValueError, match="three-component"):
        CubicAnisotropy((1, 0, 0), (0, 1, 0), 1e4, assemble=True).setup(m, Ms)


# --------------------------------------------------------------------------
# cubic-symmetry easy/hard-axis energy ordering
# --------------------------------------------------------------------------

def _energy_for_direction(m_direction, K1=1.0e4):
    domain = _cube()
    m, Ms = _fields(domain, tuple(m_direction))
    ca = CubicAnisotropy((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), K1, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)
    return ca.compute_energy()


def test_cubic_symmetry_easy_hard_axis_ordering_for_positive_k1():
    """For K1 > 0 and the standard orthonormal cubic axes, <100> is the easy
    direction (E == 0) and <111> is the hardest, with exact ratios derivable
    from the transcribed energy density: with a = m . [100] etc, E([100]) has
    (a,b,c) = (1,0,0) so every product a^2 b^2 etc vanishes; E([110]) has
    a=b=1/sqrt(2), c=0, giving a^2 b^2 = 1/4; E([111]) has a=b=c=1/sqrt(3),
    giving three terms of 1/9 each, summing to 1/3."""
    K1 = 1.0e4
    e100 = _energy_for_direction((1.0, 0.0, 0.0), K1)
    e110 = _energy_for_direction((1.0 / np.sqrt(2), 1.0 / np.sqrt(2), 0.0), K1)
    e111 = _energy_for_direction(
        (1.0 / np.sqrt(3), 1.0 / np.sqrt(3), 1.0 / np.sqrt(3)), K1)

    assert e100 == pytest.approx(0.0, abs=1e-9)
    assert (e110 - e100) == pytest.approx(K1 / 4.0, rel=1e-10)
    assert (e111 - e100) == pytest.approx(K1 / 3.0, rel=1e-10)
    # <100> easy, <110> intermediate, <111> hard.
    assert e100 < e110 < e111


# --------------------------------------------------------------------------
# K2 / K3 contributions in isolation
# --------------------------------------------------------------------------

def test_k2_contribution_in_isolation():
    """With K1 = K3 = 0, E = K2 * a^2 b^2 c^2 exactly."""
    domain = _cube()
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    u1, u2 = (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)
    K2 = 3.0e4

    m, Ms = _fields(domain, m_vec)
    ca = CubicAnisotropy(u1, u2, K1=0.0, K2=K2, K3=0.0, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    u3 = np.cross(u1, u2)
    a, b, c = (np.dot(ax, m_vec) for ax in (u1, u2, u3))
    expected = K2 * (a**2 * b**2 * c**2)
    assert ca.compute_energy() == pytest.approx(expected, rel=1e-10)


def test_k3_contribution_in_isolation():
    """With K1 = K2 = 0, E = K3 * (a^4 b^4 + b^4 c^4 + c^4 a^4) exactly."""
    domain = _cube()
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    u1, u2 = (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)
    K3 = 7.0e2

    m, Ms = _fields(domain, m_vec)
    ca = CubicAnisotropy(u1, u2, K1=0.0, K2=0.0, K3=K3, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    u3 = np.cross(u1, u2)
    a, b, c = (np.dot(ax, m_vec) for ax in (u1, u2, u3))
    expected = K3 * (a**4 * b**4 + b**4 * c**4 + c**4 * a**4)
    assert ca.compute_energy() == pytest.approx(expected, rel=1e-10)


# --------------------------------------------------------------------------
# axis handling: u3 = u1 x u2, non-orthogonal/non-unit axes silently accepted
# --------------------------------------------------------------------------

def test_u3_is_cross_product_of_u1_and_u2():
    domain = _cube()
    m, Ms = _fields(domain, (0.3, 0.4, np.sqrt(1 - 0.3**2 - 0.4**2)))
    u1, u2 = (1.0, 2.0, 0.0), (0.0, 1.0, 3.0)
    ca = CubicAnisotropy(u1, u2, K1=1.0e4, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)
    np.testing.assert_allclose(ca.u3_value, np.cross(u1, u2))


def test_non_orthogonal_non_unit_axes_are_silently_accepted():
    """Legacy ``CubicAnisotropy`` performs no normalisation and no
    orthogonality check on ``u1``/``u2`` -- it documents them as "should be
    unit vectors" but does not enforce it (see
    ``dev/dolfinx/prototype.py::cubic_anisotropy_energy``'s investigation
    note, and the legacy module's own ``cubic_anisotropy_test.py``, whose
    axes ``u1=(0,-0.7071,0.7071)``/``u2=(0,0.7071,0.7071)`` are not exactly
    unit vectors: ``0.7071**2 * 2 == 0.99980082 != 1``). This port preserves
    that behaviour exactly rather than raising or silently renormalising."""
    u1 = np.array((1.0, 0.3, 0.0))  # not unit length
    u2 = np.array((0.2, 1.0, 0.1))  # not orthogonal to u1, not unit length
    assert not np.isclose(np.linalg.norm(u1), 1.0)
    assert not np.isclose(np.dot(u1, u2), 0.0)

    domain = _cube()
    m, Ms = _fields(domain, (0.3, 0.4, np.sqrt(1 - 0.3**2 - 0.4**2)))
    ca = CubicAnisotropy(u1, u2, K1=1.0e4, K2=5.0e3, K3=1.0e2, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    np.testing.assert_allclose(ca.u1_value, u1)
    np.testing.assert_allclose(ca.u2_value, u2)
    np.testing.assert_allclose(ca.u3_value, np.cross(u1, u2))
    assert np.isfinite(ca.compute_energy())


def test_axis_must_be_three_component_vector():
    with pytest.raises(ValueError, match="three-component vector"):
        CubicAnisotropy((1.0, 0.0), (0.0, 1.0, 0.0), 1.0e4)
    with pytest.raises(ValueError, match="three-component vector"):
        CubicAnisotropy((1.0, 0.0, 0.0), (0.0, 1.0, 0.0, 0.0), 1.0e4)


# --------------------------------------------------------------------------
# by-name deferrals
# --------------------------------------------------------------------------

def test_spatially_varying_k1_k2_k3_are_supported():
    """Task 16: spatially varying cubic K1/K2/K3 (callable/Field/Function,
    placed in CG1) are now supported; the K2 varying case's native-typo
    divergence is pinned in test_variable_params_dolfinx.py. Only legacy string
    Expressions remain deferred by name."""
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("DG", 0))
    spatial = Field(scalar_space, 1.0e4)
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    m = Field(S3, (0.3, 0.4, np.sqrt(1 - 0.09 - 0.16)))
    Ms = Field(scalar_space, 8.0e5)

    for kwargs in (dict(K1=spatial), dict(K1=1.0, K2=lambda x: 1.0e4 + x[0]),
                   dict(K1=1.0, K3=spatial)):
        ca = CubicAnisotropy((1, 0, 0), (0, 1, 0), **kwargs)
        ca.setup(m, Ms, unit_length=1e-9)
        assert np.all(np.isfinite(ca.compute_field()))

    with pytest.raises(NotImplementedError, match="string Expression"):
        CubicAnisotropy((1, 0, 0), (0, 1, 0), "1.0 + x[0]")


# --------------------------------------------------------------------------
# spatially varying axes (SR1 P3.5): greenfield -- NO legacy oracle
#
# Legacy ``CubicAnisotropy.__init__`` forms ``u3 = np.cross(u1, u2)`` from the
# *raw* axes at construction, so it crashes (ValueError) on ANY callable / Field
# / Function / string axis. There is therefore no legacy contract and no
# obtainable oracle for a spatially varying axis (the frozen oracle crashes
# identically). What legacy DOES dictate and this port preserves: axes are used
# *as given* (never normalised, never orthogonalised) and ``u3 = u1 x u2`` in
# right-handed order, now evaluated per node. The witnesses below therefore
# validate against (W1) the already-oracle-validated CONSTANT-axis path via a
# constant-reduction, and (W2) the constant-axis analytic field per region --
# there is no D2-style divergence pin because there is no legacy value to
# diverge from.
# --------------------------------------------------------------------------

def _const_callable(u):
    """A spatially constant vectorized callable evaluating to the vector ``u``."""
    u = np.asarray(u, dtype=float)

    def f(x):
        return np.repeat(u[:, None], x.shape[1], axis=1)

    return f


def test_spatially_varying_axes_are_accepted():
    """SR1 P3.5: spatially varying cubic axes (callable / Field / Function) are
    now supported -- routed through the same ``axis_coefficient(..., normalise=
    False)`` / vector-CG1 Field placement the ``UniaxialAnisotropy`` axis and
    the varying-K path already use, with ``u3 = u1 x u2`` formed per node. This
    lifts the historical by-name deferral (legacy crashed in ``np.cross`` at
    construction on any varying axis -- see the module comment above), so it is
    a greenfield extension validated by the W1/W2 witnesses below, not a legacy
    port."""
    domain = _cube()
    vector_space = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    spatial_axis = Field(vector_space, (1.0, 0.0, 0.0))
    m, Ms = _fields(domain, (0.2, 0.5, np.sqrt(1.0 - 0.29)))

    for ca in (
        CubicAnisotropy(spatial_axis, (0, 1, 0), 1.0e4),        # Field axis
        CubicAnisotropy((1, 0, 0), spatial_axis, 1.0e4),        # Field axis (u2)
        CubicAnisotropy(_const_callable((1, 0, 0)), (0, 1, 0), 1.0e4),  # callable
    ):
        ca.setup(m, Ms, unit_length=1.0)
        assert np.all(np.isfinite(ca.compute_field()))


def test_string_expression_axis_still_rejected():
    """A legacy string-Expression axis is STILL refused by name -- delegated to
    ``axis_coefficient``, which raises ``NotImplementedError`` for string
    Expressions (DOLFINx has no ``Expression`` object; pass a callable). The
    varying-axis (callable/Field/Function) deferral was lifted in SR1 P3.5, but
    the string-Expression deferral is a separate, still-live limitation, so its
    exception now carries the ``axis_coefficient`` string-Expression message
    rather than the old varying-axis deferral wording."""
    with pytest.raises(NotImplementedError, match="string Expression"):
        CubicAnisotropy(("1.0", "0.0", "0.0"), (0, 1, 0), 1.0e4)
    with pytest.raises(NotImplementedError, match="string Expression"):
        CubicAnisotropy((1, 0, 0), "x[0]", 1.0e4)


def test_varying_axis_constant_reduction_matches_constant_axis():
    """W1 (constant-reduction witness), bit-for-bit. A callable axis and a Field
    axis whose values equal a spatial constant must reproduce the constant-axis
    ``CubicAnisotropy`` field AND energy to ~machine precision, on BOTH the
    ``assemble=False`` nodal path and the ``assemble=True`` box path. This
    anchors the new varying-axis path to the constant-axis path, which is the
    one already pinned to the legacy oracle (there is no varying-axis oracle;
    see the module comment). Uses a non-unit / non-orthogonal axis pair to also
    confirm the as-given contract survives the reduction."""
    domain = _cube(3)
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    K1, K2, K3 = 1.0e4, 2.0e3, 3.0e2
    u1c, u2c = (1.0, 2.0, 0.0), (0.0, 1.0, 3.0)  # non-unit, non-orthogonal
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))

    for assemble in (False, True):
        m, Ms = _fields(domain, m_vec)
        const = CubicAnisotropy(u1c, u2c, K1, K2, K3, assemble=assemble)
        const.setup(m, Ms, unit_length=1.0)

        m2, Ms2 = _fields(domain, m_vec)
        # u1 as a callable, u2 as a Field -- both equal to the constant axes.
        var = CubicAnisotropy(
            _const_callable(u1c), Field(S3, u2c), K1, K2, K3, assemble=assemble)
        var.setup(m2, Ms2, unit_length=1.0)

        np.testing.assert_allclose(
            var.compute_field(), const.compute_field(), rtol=1e-13, atol=0.0)
        np.testing.assert_allclose(
            var.compute_energy(), const.compute_energy(), rtol=1e-13, atol=0.0)


def test_piecewise_axis_nodal_field_matches_per_region_constant():
    """W2 (piecewise-region witness) on the ``assemble=False`` nodal path. A
    spatially varying axis that is piecewise-constant across two regions must
    give, at every node, exactly the constant-axis analytic field for that
    node's own axis (each node evaluates its own axis and its own
    ``u3 = u1_node x u2_node``). Region B is region A's frame rotated about z, so
    each region reduces to a known constant-axis cubic field. Asserted only on
    the exact nodal path: the ``assemble=True`` box path interpolates the CG1
    axis across the region seam (continuous), so exactness there does not hold
    and is deliberately not pinned."""
    domain = _cube(3)
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    Ms = 8.0e5
    K1, K2, K3 = 1.0e4, 2.0e3, 3.0e2
    uA1, uA2 = np.array((1.0, 0.0, 0.0)), np.array((0.0, 1.0, 0.0))
    th = 0.7
    uB1 = np.array((np.cos(th), np.sin(th), 0.0))
    uB2 = np.array((-np.sin(th), np.cos(th), 0.0))

    def piecewise(uA, uB):
        def f(x):
            out = np.empty((3, x.shape[1]))
            left = x[0] < 0.5
            out[:, left] = uA[:, None]
            out[:, ~left] = uB[:, None]
            return out

        return f

    m, Ms_field = _fields(domain, m_vec, Ms=Ms)
    ca = CubicAnisotropy(
        piecewise(uA1, uB1), piecewise(uA2, uB2), K1, K2, K3)  # assemble=False
    ca.setup(m, Ms_field, unit_length=1.0)

    coords, m_nodes = m.coords_and_values()
    left = coords[:, 0] < 0.5
    assert left.any() and (~left).any()

    H = ca.compute_field().reshape((3, -1)).T
    H_A = _analytic_field(m_nodes[left], uA1, uA2, K1, K2, K3, Ms)
    H_B = _analytic_field(m_nodes[~left], uB1, uB2, K1, K2, K3, Ms)
    np.testing.assert_allclose(H[left], H_A, rtol=1e-12, atol=0.0)
    np.testing.assert_allclose(H[~left], H_B, rtol=1e-12, atol=0.0)


def test_varying_axis_used_as_given_not_normalised():
    """As-given preservation (legacy contract). A non-unit, spatially varying
    axis is stored verbatim -- never normalised, never orthogonalised -- exactly
    as legacy used its constant axes raw (mirrors
    ``test_non_orthogonal_non_unit_axes_are_silently_accepted`` for the varying
    case)."""
    domain = _cube(2)
    m, Ms = _fields(domain, (0.3, 0.4, np.sqrt(1.0 - 0.25)))

    def u1_var(x):  # spatially varying, never unit length
        n = x.shape[1]
        return np.vstack((1.0 + x[0], 2.0 * np.ones(n), 3.0 * np.ones(n)))

    ca = CubicAnisotropy(u1_var, (0.0, 1.0, 0.0), K1=1.0e4)
    ca.setup(m, Ms, unit_length=1.0)

    coords, u1_nodes = ca.u1.coords_and_values()
    n = coords.shape[0]
    expected = np.column_stack(
        (1.0 + coords[:, 0], 2.0 * np.ones(n), 3.0 * np.ones(n)))
    np.testing.assert_allclose(u1_nodes, expected, rtol=0.0, atol=1e-13)
    # not renormalised: every node's stored axis has norm clearly != 1.
    assert np.all(np.abs(np.linalg.norm(u1_nodes, axis=1) - 1.0) > 0.1)


def test_varying_u3_is_per_node_cross_product():
    """``u3 = u1 x u2`` is evaluated PER NODE in right-handed (legacy
    ``np.cross``) order for spatially varying axes -- the stored ``u3`` Field
    equals ``np.cross(u1_node, u2_node)`` node-for-node."""
    domain = _cube(3)
    m, Ms = _fields(domain, (0.2, 0.5, np.sqrt(1.0 - 0.29)))

    def u1_var(x):
        return np.vstack(
            (np.cos(0.5 * x[0]), np.sin(0.5 * x[0]), np.zeros(x.shape[1])))

    def u2_var(x):
        return np.vstack(
            (np.zeros(x.shape[1]), np.cos(0.4 * x[1]), np.sin(0.4 * x[1])))

    ca = CubicAnisotropy(u1_var, u2_var, K1=1.0e4, K2=2.0e3, K3=3.0e2)
    ca.setup(m, Ms, unit_length=1.0)

    u1n = ca.u1.as_array().reshape(-1, 3)
    u2n = ca.u2.as_array().reshape(-1, 3)
    u3n = ca.u3.as_array().reshape(-1, 3)
    np.testing.assert_allclose(
        u3n, np.cross(u1n, u2n, axis=1), rtol=0.0, atol=1e-13)


def test_default_assemble_false_computes_energy_and_analytic_field():
    """The legacy default constructor call (``assemble`` left at its default
    ``False``) matches ``cubic_anisotropy_test.py`` exactly and now computes
    both energy and the ported native analytic effective field (previously the
    field path raised ``NotImplementedError``)."""
    domain = _cube()
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    Ms = 8.0e5
    u1, u2 = (1, 0, 0), (0, 1, 0)
    K1, K2, K3 = 1.0e4, 2.0e3, 3.0e2
    m, Ms_field = _fields(domain, m_vec, Ms=Ms)
    ca = CubicAnisotropy(u1, u2, K1, K2, K3)
    ca.setup(m, Ms_field, unit_length=1.0)

    assert ca.assemble is False
    assert np.isfinite(ca.compute_energy())

    # Task 31: compute_field() is component-blocked; per-node rows are
    # reshape((3, -1)).T (owned-vertex order), matching m.coords_and_values().
    H = ca.compute_field().reshape((3, -1)).T
    assert np.all(np.isfinite(H))
    assert np.max(np.abs(H)) > 0.0
    H_expected = _analytic_field(
        m.coords_and_values()[1], u1, u2, K1, K2, K3, Ms)
    np.testing.assert_allclose(H, H_expected, rtol=1e-12, atol=0.0)


def test_assemble_true_computes_field():
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.3, np.sqrt(1 - 0.09)))
    ca = CubicAnisotropy((1, 0, 0), (0, 1, 0), 1.0e4, 2.0e3, 3.0e2, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    assert ca.assemble is True
    field = ca.compute_field()
    assert np.all(np.isfinite(field))
    assert np.max(np.abs(field)) > 0.0


# --------------------------------------------------------------------------
# assemble=False (default): ported native analytic field
# --------------------------------------------------------------------------

MU0 = 4.0 * np.pi * 1e-7


def _analytic_field(m_vecs, u1, u2, K1, K2, K3, Ms):
    """Reference per-node cubic-anisotropy field ``H = -1/(mu0 Ms) dE/dm``.

    Hand-derived (chain rule through ``a=u1.m``, ``b=u2.m``, ``c=u3.m``) from
    the legacy energy density ``K1*(a^2 b^2 + b^2 c^2 + c^2 a^2) +
    K2*a^2 b^2 c^2 + K3*(a^4 b^4 + b^4 c^4 + c^4 a^4)``; this is the analytic
    field the legacy native routine ``compute_cubic_field`` implements for
    ``assemble=False``. Independent of the DOLFINx port under test.
    """
    u1 = np.asarray(u1, dtype=float)
    u2 = np.asarray(u2, dtype=float)
    u3 = np.cross(u1, u2)
    m_vecs = np.asarray(m_vecs, dtype=float).reshape(-1, 3)
    a = m_vecs @ u1
    b = m_vecs @ u2
    c = m_vecs @ u3
    g1 = 2 * K1 * a * (b**2 + c**2) + 2 * K2 * a * b**2 * c**2 \
        + 4 * K3 * a**3 * (b**4 + c**4)
    g2 = 2 * K1 * b * (a**2 + c**2) + 2 * K2 * b * a**2 * c**2 \
        + 4 * K3 * b**3 * (a**4 + c**4)
    g3 = 2 * K1 * c * (a**2 + b**2) + 2 * K2 * c * a**2 * b**2 \
        + 4 * K3 * c**3 * (a**4 + b**4)
    dEdm = g1[:, None] * u1 + g2[:, None] * u2 + g3[:, None] * u3
    return -(1.0 / (MU0 * Ms)) * dEdm


def test_default_assemble_false_field_matches_analytic_derivation():
    """The ported ``assemble=False`` (legacy-default) path must reproduce the
    hand-derived analytic effective field node-for-node (pure transcription of
    ``H = -1/(mu0 Ms) dE/dm``), to machine precision."""
    domain = _cube(3)
    Ms = 8.0e5
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    u1, u2 = (0.0, -0.7071, 0.7071), (0.0, 0.7071, 0.7071)
    K1, K2, K3 = -8.6e6, -1.37e7, 1.1e6

    m, Ms_field = _fields(domain, m_vec, Ms=Ms)
    ca = CubicAnisotropy(u1, u2, K1, K2, K3)  # assemble left at default False
    ca.setup(m, Ms_field, unit_length=1e-9)
    assert ca.assemble is False

    # Task 31: component-blocked field/m to owned-vertex per-node rows.
    H = ca.compute_field().reshape((3, -1)).T
    m_nodes = m.coords_and_values()[1]
    H_expected = _analytic_field(m_nodes, u1, u2, K1, K2, K3, Ms)
    np.testing.assert_allclose(H, H_expected, rtol=1e-12, atol=0.0)
    assert np.max(np.abs(H)) > 0.0


# --------------------------------------------------------------------------
# coordinate-ordered legacy oracle comparison
# --------------------------------------------------------------------------

def _oracle_box_mesh():
    extent = 0.7
    return mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (extent, extent, extent)],
        [4, 4, 4], mesh.CellType.tetrahedron)


def _oracle_m():
    def f(x):
        return np.vstack(
            (np.full(x.shape[1], 0.6), 0.8 * np.cos(2.0 * np.pi * x[0]),
             0.8 * np.sin(2.0 * np.pi * x[0]))
        )

    return f


def test_oracle_cubic_3d_field_energy():
    physical = CASE["physical_parameters"]
    domain = _oracle_box_mesh()
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    m = Field(S3, _oracle_m(), name="m")
    Ms = Field(DG, physical["Ms"]["value"], name="Ms")

    ca = CubicAnisotropy(
        physical["u1"]["value"], physical["u2"]["value"],
        physical["K1"]["value"], physical["K2"]["value"],
        physical["K3"]["value"], assemble=True)
    ca.setup(m, Ms, unit_length=physical["unit_length"]["value"])

    E = ca.compute_energy()
    # Task 31: component-blocked field -> owned-vertex per-node rows, sorted
    # against the matching owned-vertex coordinates.
    H = ca.compute_field().reshape((3, -1)).T
    coords, _ = m.coords_and_values()
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    coords_s, H_s = coords[order], H[order]

    ref_coords = np.asarray(CASE["coordinates"]["values"])
    energy_q = CASE["scalar_quantities"][0]
    assert energy_q["name"] == "energy"
    H_q = CASE["quantities"][1]
    assert H_q["name"] == "H_vertex"
    m_q = CASE["quantities"][0]
    assert m_q["name"] == "m_vertex"

    assert coords_s.shape == ref_coords.shape
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    m_coords, m_values = m.coords_and_values()
    m_order = np.lexsort((m_coords[:, 2], m_coords[:, 1], m_coords[:, 0]))
    np.testing.assert_allclose(
        m_values[m_order], np.asarray(m_q["values"]),
        atol=m_q["tolerances"]["absolute"], rtol=m_q["tolerances"]["relative"])

    e_tol = energy_q["tolerances"]
    np.testing.assert_allclose(
        E, energy_q["value"], atol=e_tol["absolute"], rtol=e_tol["relative"])
    H_tol = H_q["tolerances"]
    np.testing.assert_allclose(
        H_s, np.asarray(H_q["values"]), atol=H_tol["absolute"],
        rtol=H_tol["relative"])


# --------------------------------------------------------------------------
# native (assemble=False) field oracle: per-term isolation + K2 typo evidence
# --------------------------------------------------------------------------

_NATIVE_FIXTURE = os.path.join(
    os.path.dirname(__file__), "fixtures", "cubic_anisotropy_native_oracle.json")
NATIVE_ORACLE = json.load(open(_NATIVE_FIXTURE))


def _native_case_port_field(case):
    """Compute the ported assemble=False analytic field for a native-oracle
    case, sorted lexicographically to match the fixture ordering."""
    physical = case["physical_parameters"]
    domain = _oracle_box_mesh()
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    m = Field(S3, _oracle_m(), name="m")
    Ms = Field(DG, physical["Ms"]["value"], name="Ms")

    ca = CubicAnisotropy(
        physical["u1"]["value"], physical["u2"]["value"],
        physical["K1"]["value"], physical["K2"]["value"],
        physical["K3"]["value"])  # assemble left at default False
    assert ca.assemble is False
    ca.setup(m, Ms, unit_length=physical["unit_length"]["value"])

    # Task 31: component-blocked field -> owned-vertex per-node rows.
    H = ca.compute_field().reshape((3, -1)).T
    coords, _ = m.coords_and_values()
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    return H[order], coords[order]


@pytest.mark.parametrize("case_name", ["k1_only", "k3_only", "all_nonzero"])
def test_native_oracle_pure_transcription(case_name):
    """K1-only, K3-only, and all-nonzero native (assemble=False) fields are a
    pure transcription of the legacy native analytic routine, so the port must
    match the legacy oracle closely: measured relative error is ~1e-15 across
    these cases, asserted here at the fixture's declared ``rtol=1e-11`` (far
    tighter than the fixture's floating-point-noise tolerance would strictly
    require)."""
    case = NATIVE_ORACLE["cases"][case_name]
    H_s, coords_s = _native_case_port_field(case)

    ref_coords = np.asarray(case["coordinates"]["values"])
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    H_q = case["quantities"][1]
    assert H_q["name"] == "H_vertex"
    ref_H = np.asarray(H_q["values"])
    scale = np.abs(ref_H).max()
    np.testing.assert_allclose(H_s, ref_H, rtol=1e-11, atol=1e-11 * scale)


def test_native_oracle_k2_typo_is_dormant_for_constant_k2():
    """K2-only native-field evidence for the ``native/src/llg/energy.cc:116``
    typo (``hz[i] += K2[2]*(...)`` -- fixed node index ``2`` where every other
    line uses per-node ``K2[i]``).

    Because ``K2`` is spatially constant here the nodal ``K2`` array is
    uniform, so ``K2[2] == K2[i]`` and the typo is numerically dormant: the
    legacy native field equals the *correct* hand-derived analytic field to
    floating-point noise. This test pins that known fact as executable
    evidence -- the correct derivation (computed independently from the
    fixture's own ``m_vertex``) reproduces the legacy native ``H_vertex``,
    including the ``hz`` component the typo touches."""
    case = NATIVE_ORACLE["cases"]["k2_only"]
    physical = case["physical_parameters"]
    K1 = physical["K1"]["value"]
    K2 = physical["K2"]["value"]
    K3 = physical["K3"]["value"]
    assert (K1, K3) == (0, 0) and K2 != 0  # genuinely K2-isolated

    m_q = case["quantities"][0]
    assert m_q["name"] == "m_vertex"
    m_vertex = np.asarray(m_q["values"])
    ref_H = np.asarray(case["quantities"][1]["values"])

    H_correct = _analytic_field(
        m_vertex, physical["u1"]["value"], physical["u2"]["value"],
        K1, K2, K3, physical["Ms"]["value"])

    scale = np.abs(ref_H).max()
    # Whole field (incl. the hz component the typo indexes) matches the
    # correct derivation -> typo demonstrably dormant for constant K2.
    np.testing.assert_allclose(H_correct, ref_H, rtol=1e-11, atol=1e-11 * scale)

    # And the port (correct field) reproduces the native oracle too.
    H_port, _ = _native_case_port_field(case)
    np.testing.assert_allclose(H_port, ref_H, rtol=1e-11, atol=1e-11 * scale)


@pytest.mark.parametrize("case_name", ["k2_only", "all_nonzero"])
def test_box_field_converges_to_analytic_field_under_refinement(case_name):
    """Independent arbiter for the analytic (assemble=False) field: the
    box-assemble (assemble=True) weak-form-derivative field is a distinct
    discretisation that must converge toward the *analytic* nodal field (this
    port's assemble=False output), not toward the buggy K2[2] variant, as the
    mesh is refined. Asserts monotone decrease of the relative L2 gap across
    three refinement levels."""
    case = NATIVE_ORACLE["cases"][case_name]
    physical = case["physical_parameters"]
    u1, u2 = physical["u1"]["value"], physical["u2"]["value"]
    K1 = physical["K1"]["value"]
    K2 = physical["K2"]["value"]
    K3 = physical["K3"]["value"]
    Ms_value = physical["Ms"]["value"]

    gaps = []
    for n in (2, 4, 8):
        domain = mesh.create_box(
            MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (0.7, 0.7, 0.7)],
            [n, n, n], mesh.CellType.tetrahedron)
        S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
        DG = fem.functionspace(domain, ("DG", 0))
        m = Field(S3, _oracle_m(), name="m")
        Ms = Field(DG, Ms_value, name="Ms")

        analytic = CubicAnisotropy(u1, u2, K1, K2, K3)
        analytic.setup(m, Ms, unit_length=1e-9)
        H_analytic = analytic.compute_field()

        box = CubicAnisotropy(u1, u2, K1, K2, K3, assemble=True)
        box.setup(m, Ms, unit_length=1e-9)
        H_box = box.compute_field()

        gaps.append(
            np.linalg.norm(H_box - H_analytic) / np.linalg.norm(H_analytic))

    assert gaps[0] > gaps[1] > gaps[2], gaps
    assert gaps[-1] < gaps[0]  # net convergence


# --------------------------------------------------------------------------
# Simulation integration
# --------------------------------------------------------------------------

def test_cubic_anisotropy_added_to_simulation_directly():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="cubic_anis_direct")
    sim.set_m((0.3, 0.4, np.sqrt(1 - 0.09 - 0.16)))
    sim.add(CubicAnisotropy(
        (1, 0, 0), (0, 1, 0), 1.0e4, 2.0e3, 3.0e2, assemble=True))
    assert sim.has_interaction("CubicAnisotropy")
    assert np.isfinite(sim.total_energy())
    assert np.all(np.isfinite(sim.effective_field()))


def test_cubic_anisotropy_default_assemble_effective_field_works():
    """A *default-constructed* (``assemble=False``) CubicAnisotropy now
    contributes a finite effective field through ``Simulation`` -- the legacy
    native analytic path, previously deferred by name."""
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="cubic_anis_default")
    sim.set_m((0.3, 0.4, np.sqrt(1 - 0.09 - 0.16)))
    sim.add(CubicAnisotropy((1, 0, 0), (0, 1, 0), 1.0e4))  # default assemble=False
    assert np.isfinite(sim.total_energy())
    field = sim.effective_field()
    assert np.all(np.isfinite(field))
    assert np.max(np.abs(field)) > 0.0


def test_cubic_anisotropy_affects_dynamics():
    """A cubic-anisotropy-only simulation, started away from an easy axis,
    must precess/relax under a genuinely nonzero effective field -- i.e. the
    interaction is actually wired into the LLG dynamics, not just present in
    the energy bookkeeping."""
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="cubic_anis_dynamics")
    # A generic, low-symmetry direction (not aligned with any easy/hard axis
    # of the standard cubic axes below), so the effective field is not
    # parallel to m and the LLG torque m x H_eff is genuinely nonzero.
    m0 = np.array((1.0, 0.3, 0.1))
    m0 /= np.linalg.norm(m0)
    sim.set_m(tuple(m0))
    sim.alpha = 0.5
    sim.add(CubicAnisotropy(
        (1, 0, 0), (0, 1, 0), 1.0e4, assemble=True))

    field0 = sim.effective_field()
    assert np.max(np.abs(field0)) > 0.0

    sim.run_until(1e-9)
    m_after = sim.m.reshape((3, -1)).T[0]
    assert not np.allclose(m_after, m0, atol=1e-6)


def test_default_assemble_false_cubic_anisotropy_affects_dynamics():
    """The legacy-default constructor (``assemble=False``, native analytic
    field) must now drive genuine LLG dynamics through ``Simulation`` -- the
    regression this fix closes. Same low-symmetry start as the assemble=True
    dynamics check; asserts m actually moves under the analytic effective
    field, not merely that no exception is raised."""
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(
        box, 8.6e5, unit_length=1e-9, name="cubic_anis_default_dynamics")
    m0 = np.array((1.0, 0.3, 0.1))
    m0 /= np.linalg.norm(m0)
    sim.set_m(tuple(m0))
    sim.alpha = 0.5
    sim.add(CubicAnisotropy((1, 0, 0), (0, 1, 0), 1.0e4))  # default assemble=False

    field0 = sim.effective_field()
    assert np.max(np.abs(field0)) > 0.0

    sim.run_until(1e-9)
    m_after = sim.m.reshape((3, -1)).T[0]
    assert not np.allclose(m_after, m0, atol=1e-6)
