"""Direct DOLFINx FK demag port (Task 11b + SR1 P5.2 minimal-diff transcription).

This file has two clearly separated parts:

1. A MINIMAL-DIFF transcription of the master sphere-analytic unit tests from
   ``src/finmag/energies/demag/fk_demag_test.py`` (git ``b5015c5a``). Function
   names, ordering, assertion structure and TOLERANCES are kept identical to
   master; the only differences are (a) dolfin->dolfinx API changes (each
   annotated inline), (b) the py2->py3 ``print`` conversion, and (c) explanatory
   comments. Every restored master tolerance passes VERBATIM under DOLFINx --
   measured values are recorded next to each assertion so any future drift is
   visible in a side-by-side diff.

2. The sophisticated NEW-under-DOLFINx tests (golden-BEM extraction, per-case
   oracle-fixture compares, analytic-cube factor, Krylov-residual isolation,
   deferred-solver contracts) which have no master ancestor. They live below the
   ``NEW under DOLFINx`` banner and are unchanged.

The NEW tests validate the ported ``finmag.energies.demag.fk_demag.FKDemag``
and its coordinate-driven boundary-node ordering against:

- the Task 11a golden BEM matrix, reproduced *bit-for-bit* through the new
  DOLFINx boundary extraction after the coordinate-induced permutation (the
  silent-permutation guard the physics contract demands);
- the analytic uniformly-magnetised-cube demag factor (average H = -Ms/3,
  energy = mu0 Ms^2 V / 6);
- coordinate-ordered legacy FEniCS-2019 oracle references (energy, average
  field, and full pointwise field) generated at the frozen oracle commit
  ``ba9280934e188d7f3800e7b9865e70a9422f7687`` for a unit cube and the barmini
  bar, and a tight-Krylov-tolerance variant of the cube case (schema-v1
  fixture, ``src/finmag/tests/fixtures/fk_demag_oracle.json``, regenerated by
  ``src/finmag/tests/fixtures/gen_fk_demag_oracle.py``).

Review round 1, Finding 1: the standard-tolerance (1e-6) pointwise gap
between the port and the oracle (~6.4e-6 relative to |H|_max) is
**demonstrated** (not merely asserted) to come from the oracle fixture's own
frozen 1e-6 Krylov solves, not from a systematic method difference. Tightening
*both* sides to a KSP rtol/atol of 1e-12 collapses the pointwise gap to
~1.4e-12 and the energy gap to ~5.5e-14 -- see
``test_oracle_cube_tight_tolerance_isolates_krylov_residual`` below, which
pins this empirically rather than asserting it in prose.

[Claude Opus 4.8], [Claude Sonnet 5]
"""

import json
import os
import time
from math import pi

import numpy as np
import pytest
from mpi4py import MPI

import basix.ufl
import dolfinx.fem as fem
import dolfinx.mesh as dm

from finmag.field import Field, associated_scalar_space, evaluate_at_point
from finmag.energies import Demag
from finmag.energies.demag import Demag2D, MacroGeometry
from finmag.energies.demag.fk_demag import FKDemag, boundary_bem_arrays
from finmag.native.bem_arrays import compute_bem_fk_from_arrays
from finmag.tests.test_native_bem_arrays_dolfinx import (
    CUBE_COORDS, CUBE_CELLS, GOLDEN_BEM_FK)
from finmag.util.consts import mu0  # master imported mu0 from consts (== 4*pi*1e-7)
from finmag.util.meshes import sphere, box


# ==========================================================================
# MINIMAL-DIFF transcription of master fk_demag_test.py (git b5015c5a).
# dolfin->dolfinx changes are annotated inline; tolerances are master's,
# each with the measured DOLFINx value recorded beside it.
# ==========================================================================

radius = 1.0
maxh = 0.2
unit_length = 1e-9
volume = 4 * pi * (radius * unit_length) ** 3 / 3


def setup_demag_sphere(Ms):
    # meshes.sphere now returns a DOLFINx mesh via the netgen/gmsh backend
    # (master got a dolfin.Mesh). save_result=False is the one deviation from
    # master's call: the default (True) caches the mesh as sphere-1-0_2.{h5,xdmf}
    # in the CWD, littering the repo root on every gate run (the artifacts are
    # not gitignored). The test does not need the cache, so we disable it.
    mesh = sphere(r=radius, maxh=maxh, save_result=False)
    # df.FunctionSpace(mesh, 'DG', 0) -> dolfinx.fem.functionspace((family, degree))
    Ms_field = Field(fem.functionspace(mesh, ("DG", 0)), Ms)
    # df.VectorFunctionSpace(mesh, "Lagrange", 1) -> functionspace with shape=(3,)
    S3 = fem.functionspace(mesh, ("Lagrange", 1, (3,)))
    # master built df.Function(S3) + assign(df.Constant((1,0,0))); the DOLFINx
    # Field accepts the constant tuple directly.
    m = Field(S3, (1, 0, 0))
    demag = FKDemag()
    demag.setup(m, Ms_field, unit_length)
    return demag


def test_interaction_accepts_name():
    """
    Check that the interaction accepts a 'name' argument and has a 'name' attribute.
    """
    demag = FKDemag(name='MyDemag')
    assert hasattr(demag, 'name')


def test_demag_field_for_uniformly_magnetised_sphere():
    demag = setup_demag_sphere(1)
    H = demag.compute_field().reshape((3, -1))
    H_expected = np.array([-1.0 / 3.0, 0.0, 0.0])
    print("Got demagnetising field H =\n{}.\nExpected mean H = {}.".format(
        H, H_expected))

    TOL = 7e-3  # master 7e-3; measured DOLFINx max diff ~4.4e-3 -> passes verbatim
    diff = np.max(np.abs(H - H_expected[:, np.newaxis]), axis=1)
    print("Maximum difference to expected result per axis is {}. Comparing to limit {}.".format(diff, TOL))
    assert np.max(diff) < TOL

    TOL = 8e-3  # master 8e-3; measured DOLFINx max spread ~5.0e-3 -> passes verbatim
    spread = np.abs(H.max(axis=1) - H.min(axis=1))
    print("The values spread {} per axis. Comparing to limit {}.".format(spread, TOL))
    assert np.max(spread) < TOL


@pytest.mark.skip(reason="netgen box() mesh + wall-clock timing comparison "
                         "deferred under DOLFINx; master already marked this "
                         "xfail. Assertions preserved verbatim for the record.")
@pytest.mark.slow  # this test needs a minute to complete
def test_thin_film_argument_saves_time_on_thin_film():
    mesh = box(0, 0, 0, 500, 50, 1, maxh=2.0, directory="meshes")
    Ms = Field(fem.functionspace(mesh, ("DG", 0)), 8e5)  # df.FunctionSpace -> functionspace
    unit_length = 1e-9
    S3 = fem.functionspace(mesh, ("Lagrange", 1, (3,)))  # df.VectorFunctionSpace -> shape=(3,)
    m = Field(S3, (0, 0, 1))  # df.Function+assign(Constant((0,0,1))) -> constant tuple

    demag = FKDemag()
    demag.setup(m, Ms, unit_length)
    now = time.time()
    H = demag.compute_field()
    elapsed = time.time() - now
    del(demag)

    demag = FKDemag(thin_film=True)
    demag.setup(m, Ms, unit_length)
    now = time.time()
    H = demag.compute_field()
    elapsed_thin_film = time.time() - now

    saved_relative = (elapsed - elapsed_thin_film) / elapsed
    print("FKDemag thin film settings saved {:.1%} of time.".format(saved_relative))
    assert elapsed_thin_film < elapsed
    # This was 20% initially, but in order to make tests more robust this
    # value is reduced to 5%
    assert saved_relative > 0.05


def test_demag_energy_for_uniformly_magnetised_sphere():
    Ms = 800e3
    demag = setup_demag_sphere(Ms)
    E = demag.compute_energy()
    # -mu0/2 Integral H * M with H = - M / 3
    E_expected = (1.0 / 6.0) * mu0 * Ms ** 2 * volume
    print("Got E = {}. Expected E = {}.".format(E, E_expected))

    REL_TOL = 3e-2  # master 3e-2; measured DOLFINx rel_diff ~2.1e-2 -> passes verbatim
    rel_diff = abs(E - E_expected) / abs(E_expected)
    print("Relative difference is {:.3g}%. Comparing to limit {:.3g}%.".format(
        100 * rel_diff, 100 * REL_TOL))
    assert rel_diff < REL_TOL


def test_energy_density_for_uniformly_magnetised_sphere():
    Ms = 800e3
    demag = setup_demag_sphere(Ms)
    rho = demag.energy_density()

    # -mu0/2 Integral H * M with H = - M / 3
    E_expected = (1.0 / 6.0) * mu0 * Ms ** 2 * volume
    rho_expected = E_expected / volume
    print("Got mean rho = {:.3e}. Expected rho = {:.3e}.".format(np.mean(rho), rho_expected))

    REL_TOL = 1.7e-2  # master 1.7e-2; measured DOLFINx max rel_diff ~1.1e-2 -> passes verbatim
    rel_diff = np.max(np.abs(rho - rho_expected)) / abs(rho_expected)
    print("Maximum relative difference = {:.3g}%. Comparing to limit {:.3g}%.".format(
        100 * rel_diff, 100 * REL_TOL))
    assert rel_diff < REL_TOL


def test_energy_density_for_uniformly_magnetised_sphere_as_function():
    Ms = 800e3
    demag = setup_demag_sphere(Ms)
    rho = demag.energy_density_function()
    print("Probing the energy density at the center of the sphere.")
    # master called the dolfin Function directly: rho([0,0,0]). DOLFINx
    # fem.Function is not point-callable, so use the shared evaluate_at_point
    # helper. The centre [0,0,0] is strictly interior, so it is safe from the
    # known evaluate_at_point outer-face point-location defect.
    rho_center = evaluate_at_point(rho, [0.0, 0.0, 0.0])

    # -mu0/2 Integral H * M with H = - M / 3
    E_expected = (1.0 / 6.0) * mu0 * Ms ** 2 * volume
    rho_expected = E_expected / volume
    print("Got rho = {:.3e}. Expected rho = {:.3e}.".format(rho_center, rho_expected))

    REL_TOL = 1.3e-2  # master 1.3e-2; measured DOLFINx rel_diff ~7.4e-3 -> passes verbatim
    rel_diff = np.max(np.abs(rho_center - rho_expected)) / abs(rho_expected)
    print("Maximum relative difference = {:.3g}%. Comparing to limit {:.3g}%.".format(
        100 * rel_diff, 100 * REL_TOL))
    assert rel_diff < REL_TOL


def test_regression_Ms_numpy_type():
    mesh = sphere(r=radius, maxh=maxh, save_result=False)  # save_result=False: avoid repo-root litter (see setup_demag_sphere)
    S3 = fem.functionspace(mesh, ("Lagrange", 1, (3,)))  # df.VectorFunctionSpace -> shape=(3,)

    m = Field(S3, (1, 0, 0))  # df.Function+assign(Constant((1,0,0))) -> constant tuple

    Ms = np.sqrt(6.0 / mu0)  # math.sqrt(6.0 / mu0) would work
    demag = FKDemag()
    Ms_field = Field(fem.functionspace(mesh, ("DG", 0)), Ms)  # df.FunctionSpace -> functionspace
    demag.setup(m, Ms_field, unit_length)  # this used to fail


# ==========================================================================
# ===== NEW under DOLFINx (no master ancestor) =============================
# ==========================================================================
# Golden-BEM extraction guards, per-case oracle-fixture comparisons, the
# analytic uniformly-magnetised CUBE factor (10% -- the Kuhn main-diagonal
# split breaks exact cubic symmetry, so 1/3 per axis is only approached, see
# test comments), the Krylov-residual isolation, and the deferred-solver
# contracts below have no ancestor in master fk_demag_test.py.

_FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures",
                        "fk_demag_oracle.json")
ORACLE = json.load(open(_FIXTURE))
CASES = ORACLE["cases"]

# Bit-for-bit BEM reproduction is unrelated to the oracle fixture and stays a
# fixed local constant; all other tolerances are per-case, read from the
# fixture's own 'quantities'/'scalar_quantities' entries (Finding 2).
TOL_BEM_GOLDEN = 1e-13


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def _kuhn_cube():
    """DOLFINx unit cube with the exact 6-tet main-diagonal (Kuhn) split that
    legacy ``UnitCubeMesh(1, 1, 1)`` uses, so its boundary triangulation is the
    same surface the Task 11a golden matrix was captured on."""
    tets = np.array([
        [0, 1, 2, 7], [0, 1, 3, 7], [0, 4, 2, 7],
        [0, 4, 5, 7], [0, 6, 3, 7], [0, 6, 5, 7],
    ], dtype=np.int64)
    el = basix.ufl.element("Lagrange", "tetrahedron", 1, shape=(3,))
    return dm.create_mesh(MPI.COMM_WORLD, tets, el, CUBE_COORDS.copy())


def _coord_permutation(coords, reference):
    """Index array ``perm`` s.t. ``coords[perm[k]]`` matches ``reference[k]``."""
    perm = np.empty(len(reference), dtype=int)
    for k, rc in enumerate(reference):
        perm[k] = int(np.argmin(np.linalg.norm(coords - rc, axis=1)))
    assert len(set(perm.tolist())) == len(reference)
    return perm


def _demag_on(mesh, m_vec, Ms, unit_length, parameters=None):
    S3 = fem.functionspace(mesh, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(mesh, ("DG", 0))
    mv = np.asarray(m_vec, dtype=float)
    mv = mv / np.linalg.norm(mv)
    m = Field(S3, tuple(mv))
    Ms_field = Field(DG, Ms)
    demag = FKDemag(parameters=parameters)
    demag.setup(m, Ms_field, unit_length)
    return demag, S3


# --------------------------------------------------------------------------
# boundary-ordering contract, pinned to the 11a golden matrix
# --------------------------------------------------------------------------

def test_extraction_reproduces_golden_bem_kuhn():
    """The DOLFINx boundary extraction reproduces the 11a golden matrix
    bit-for-bit (up to the coordinate-induced permutation) on the exact legacy
    Kuhn triangulation."""
    mesh = _kuhn_cube()
    S1 = fem.functionspace(mesh, ("Lagrange", 1))
    coords, cells, b2g = boundary_bem_arrays(mesh, S1)
    bem, _ = compute_bem_fk_from_arrays(coords, cells,
                                        np.asarray(b2g, dtype=np.int64))
    perm = _coord_permutation(coords, CUBE_COORDS)
    permuted = bem[np.ix_(perm, perm)]
    np.testing.assert_allclose(permuted, GOLDEN_BEM_FK, rtol=0,
                               atol=TOL_BEM_GOLDEN)


def test_extraction_reproduces_golden_bem_create_unit_cube():
    """The realistic ``create_unit_cube(1,1,1)`` path also reproduces golden
    (DOLFINx uses the same Kuhn split), proving the extraction is not tied to a
    hand-built mesh."""
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 1, 1, 1)
    S1 = fem.functionspace(mesh, ("Lagrange", 1))
    coords, cells, b2g = boundary_bem_arrays(mesh, S1)
    bem, _ = compute_bem_fk_from_arrays(coords, cells,
                                        np.asarray(b2g, dtype=np.int64))
    perm = _coord_permutation(coords, CUBE_COORDS)
    permuted = bem[np.ix_(perm, perm)]
    np.testing.assert_allclose(permuted, GOLDEN_BEM_FK, rtol=0,
                               atol=TOL_BEM_GOLDEN)


def test_boundary_triangles_are_outward_oriented():
    """Every extracted boundary triangle winds so its normal points out of the
    cube (the winding the Lindholm double-layer kernel assumes)."""
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 2, 2, 2)
    S1 = fem.functionspace(mesh, ("Lagrange", 1))
    coords, cells, _ = boundary_bem_arrays(mesh, S1)
    centre = coords.mean(axis=0)
    for tri in cells:
        p0, p1, p2 = coords[tri]
        normal = np.cross(p1 - p0, p2 - p0)
        outward = ((p0 + p1 + p2) / 3.0) - centre
        assert np.dot(normal, outward) > 0.0


def test_bem_row_sum_identity_through_extraction():
    """FK BEM row sums equal -1 through the DOLFINx extraction (closed-surface
    solid-angle identity), a triangulation-independent sanity check."""
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 3, 3, 3)
    S1 = fem.functionspace(mesh, ("Lagrange", 1))
    coords, cells, b2g = boundary_bem_arrays(mesh, S1)
    bem, _ = compute_bem_fk_from_arrays(coords, cells,
                                        np.asarray(b2g, dtype=np.int64))
    np.testing.assert_allclose(bem.sum(axis=1), -np.ones(len(coords)),
                               rtol=0, atol=1e-10)


def test_b2g_map_indexes_scalar_dofs_by_coordinate():
    """``b2g`` maps each BEM-local node to the S1 dof at the same coordinate."""
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 2, 2, 2)
    S1 = fem.functionspace(mesh, ("Lagrange", 1))
    coords, _, b2g = boundary_bem_arrays(mesh, S1)
    dof_coords = S1.tabulate_dof_coordinates()
    np.testing.assert_allclose(dof_coords[b2g], coords, rtol=0, atol=1e-12)


def test_sorted_index_winding_produces_wrong_bem_with_unchanged_row_sums():
    """Pins the critical 11b discovery: naive ascending-index ("sorted")
    facet winding -- the winding DOLFINx's raw facet-vertex connectivity
    returns, before ``boundary_bem_arrays`` applies its outward-orientation
    flip -- produces a BEM matrix whose row sums are STILL approx -1 (the
    closed-surface solid-angle identity survives the corrupted winding), yet
    individual entries are wrong by far more than any legitimate
    discretisation/solver tolerance (~0.18 max-abs here). This demonstrates
    that ``test_bem_row_sum_identity_through_extraction`` alone cannot catch
    a winding/orientation bug -- only the golden-matrix pin can."""
    mesh = _kuhn_cube()
    S1 = fem.functionspace(mesh, ("Lagrange", 1))
    coords, oriented_cells, b2g = boundary_bem_arrays(mesh, S1)
    b2g = np.asarray(b2g, dtype=np.int64)

    # Deliberately corrupt the winding: sort each triangle's BEM-local vertex
    # indices ascending instead of using the outward-oriented winding.
    sorted_cells = np.sort(oriented_cells, axis=1)
    assert np.any(np.any(sorted_cells != oriented_cells, axis=1)), (
        "test setup: sorting must actually change at least one triangle's "
        "winding, or this test would not exercise the discovery"
    )

    bem_sorted, _ = compute_bem_fk_from_arrays(coords, sorted_cells, b2g)
    bem_oriented, _ = compute_bem_fk_from_arrays(coords, oriented_cells, b2g)

    np.testing.assert_allclose(bem_sorted.sum(axis=1), -np.ones(len(coords)),
                               rtol=0, atol=1e-10)
    assert np.abs(bem_sorted - bem_oriented).max() > 0.1


# --------------------------------------------------------------------------
# analytic uniformly-magnetised cube
# --------------------------------------------------------------------------

def test_uniform_cube_average_demag_factor():
    """A uniformly magnetised cube has average demag field -Ms/3 (each axis
    demag factor 1/3). The coarse FK mesh converges toward it from above."""
    Ms = 8.0e5
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 6, 6, 6)
    demag, _ = _demag_on(mesh, (1, 0, 0), Ms, 1e-9)
    avg = demag.average_field()
    # dominant component negative and within ~10% of the analytic -Ms/3
    assert avg[0] < 0.0
    assert abs(avg[0] / (-Ms / 3.0) - 1.0) < 0.1
    # transverse averages are small (Kuhn split breaks exact cubic symmetry)
    assert abs(avg[1]) < 0.05 * Ms
    assert abs(avg[2]) < 0.05 * Ms


def test_uniform_cube_energy_matches_analytic():
    """E = mu0 Ms^2 V / 6 for a uniformly magnetised cube."""
    Ms = 8.0e5
    unit_length = 1e-9
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 6, 6, 6)
    demag, _ = _demag_on(mesh, (1, 0, 0), Ms, unit_length)
    E = demag.compute_energy()
    V = (1.0 * unit_length) ** 3
    E_expected = (1.0 / 6.0) * mu0 * Ms ** 2 * V
    assert abs(E - E_expected) / E_expected < 0.1


# --------------------------------------------------------------------------
# coordinate-ordered legacy oracle comparisons
# --------------------------------------------------------------------------

def _scalar_quantity(case, name):
    for q in case["scalar_quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _quantity(case, name):
    for q in case["quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _oracle_compare(case_name, mesh, m_vec, Ms, unit_length, parameters=None):
    """Compare the port against a fixture case, with every tolerance read
    from the fixture itself (Finding 2) rather than hardcoded in the test."""
    case = CASES[case_name]
    demag, S3 = _demag_on(mesh, m_vec, Ms, unit_length, parameters=parameters)
    E = demag.compute_energy()
    avg = demag.average_field()
    # Task 31: component-blocked field -> owned-vertex per-node rows, sorted
    # against the matching owned-vertex coordinates.
    H = demag.compute_field().reshape((3, -1)).T
    n_owned = mesh.geometry.index_map().size_local
    coords = mesh.geometry.x[:n_owned, : mesh.geometry.dim]
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    coords_s, H_s = coords[order], H[order]

    ref_coords = np.asarray(case["coordinates"]["values"])
    energy_q = _scalar_quantity(case, "energy")
    avg_q = _scalar_quantity(case, "average_field")
    H_q = _quantity(case, "H_vertex")
    ref_E = energy_q["value"]
    ref_avg = np.asarray(avg_q["value"])
    ref_H = np.asarray(H_q["values"])

    # meshes coincide vertex-for-vertex (create_box == legacy BoxMesh)
    assert coords_s.shape == ref_coords.shape
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    e_tol = energy_q["tolerances"]
    np.testing.assert_allclose(E, ref_E, atol=e_tol["absolute"],
                               rtol=e_tol["relative"])
    avg_tol = avg_q["tolerances"]
    np.testing.assert_allclose(avg, ref_avg, atol=avg_tol["absolute"],
                               rtol=avg_tol["relative"])
    H_tol = H_q["tolerances"]
    np.testing.assert_allclose(H_s, ref_H, atol=H_tol["absolute"],
                               rtol=H_tol["relative"])


def test_oracle_cube_field_energy():
    _oracle_compare("cube", dm.create_unit_cube(MPI.COMM_WORLD, 4, 4, 4),
                    (1, 0, 0), 8.0e5, 1e-9)


def test_oracle_barmini_field_energy():
    """barmini-class workflow: 3x3x10 nm bar, m=(1,0,1), compiled FK demag,
    compared to the frozen legacy oracle on the coordinate-identical mesh."""
    mesh = dm.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (3.0, 3.0, 10.0)],
        [2, 2, 4], dm.CellType.tetrahedron)
    _oracle_compare("barmini", mesh, (1, 0, 1), 0.86e6, 1e-9)


def test_oracle_cube_tight_tolerance_isolates_krylov_residual():
    """Finding 1 (Task 11b review round 1): tightening *both* the port's KSP
    and the oracle's own legacy Krylov solves to rtol/atol 1e-12 collapses the
    standard-tolerance (1e-6) pointwise gap (~6.4e-6 relative to |H|_max) to
    ~1e-12. This demonstrates -- rather than merely asserts -- that the
    standard-tolerance residual is attributable to the oracle fixture's own
    frozen 1e-6 solves, not a systematic method difference between the port
    and the legacy formulation. See ``cube_tight_tolerance`` in the fixture
    and ``gen_fk_demag_oracle.py`` for how the reference datum was produced
    (via ``dev/bin/run-legacy-oracle`` with tightened ``FKDemag`` solver
    parameters)."""
    tight = {
        "phi_1": {"relative_tolerance": 1e-12, "absolute_tolerance": 1e-12,
                  "maximum_iterations": int(1e5)},
        "phi_2": {"relative_tolerance": 1e-12, "absolute_tolerance": 1e-12,
                  "maximum_iterations": int(1e5)},
    }
    _oracle_compare("cube_tight_tolerance",
                    dm.create_unit_cube(MPI.COMM_WORLD, 4, 4, 4),
                    (1, 0, 0), 8.0e5, 1e-9, parameters=tight)


# --------------------------------------------------------------------------
# interaction contract + energy_density
# --------------------------------------------------------------------------

def test_interaction_contract():
    demag = FKDemag(name="MyDemag")
    assert demag.name == "MyDemag"
    assert demag.in_jacobian is False
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 3, 3, 3)
    demag, S3 = _demag_on(mesh, (1, 0, 0), 8.0e5, 1e-9)
    # compute_field returns a flat owned array matching m's owned dofs
    m = Field(S3, (1.0, 0.0, 0.0))
    assert demag.compute_field().size == m.as_array().size


def test_energy_density_integrates_to_total_energy():
    Ms = 8.0e5
    unit_length = 1e-9
    mesh = dm.create_unit_cube(MPI.COMM_WORLD, 4, 4, 4)
    demag, _ = _demag_on(mesh, (1, 0, 0), Ms, unit_length)
    rho = demag.energy_density()
    total = demag.compute_energy()
    # sum(rho_i * V_i) ~ total energy; nodal volumes are mesh-unit, scaled here
    V_nodal = demag._nodal_volumes_S1 * unit_length ** demag.dim
    assert abs(np.dot(rho, V_nodal) - total) / abs(total) < 1e-6
    fn = demag.energy_density_function()
    assert fn.x.array.size >= rho.size


# --------------------------------------------------------------------------
# deferred variants raise by name
# --------------------------------------------------------------------------

def test_demag_factory_returns_fk_demag():
    d = Demag()
    assert isinstance(d, FKDemag)
    d2 = Demag(solver="FK")
    assert isinstance(d2, FKDemag)


def test_deferred_demag_solvers_raise_by_name():
    # GCR stays deferred (Task 29 candidate); Treecode is now ported (Task 23,
    # see test_treecode_pbc_demag_dolfinx.py) and no longer raises by name.
    with pytest.raises(NotImplementedError, match="GCR"):
        Demag(solver="GCR")
    with pytest.raises(NotImplementedError, match="not implemented"):
        Demag(solver="Nonexistent")


def test_demag2d_still_deferred_macrogeometry_ported():
    # Demag2D stays deferred (Task 23 decision: heavy MeshEditor/Expression
    # coupling, no treecode dependency); MacroGeometry is ported and constructs.
    with pytest.raises(NotImplementedError, match="Demag2D"):
        Demag2D()
    mg = MacroGeometry(nx=3, ny=1, dx=10.0, dy=10.0)
    assert len(mg.compute_Ts(None)) == 3


def test_lu_solver_type_raises_by_name():
    with pytest.raises(NotImplementedError, match="LU"):
        FKDemag(solver_type="LU")


def test_finmagrc_solver_type_option_raises_by_name(tmp_path, monkeypatch):
    """Finding 4 (Task 11b review round 1): legacy ``FKDemag`` read
    ``demag/solver_type`` from ``.finmagrc`` when the kwarg was not given; the
    port had silently dropped that read, so a user config requesting e.g.
    'LU' would silently get Krylov instead. ``finmag.util.configuration`` has
    no env-var override, only a hardcoded homedir path list
    (``CONFIGURATION_FILES``), so that list is monkeypatched to a temp file --
    the module's own test-safe seam -- to exercise the real configparser
    code path without touching the developer's actual ``~/.finmagrc``."""
    from finmag.util import configuration as config_module

    finmagrc = tmp_path / "finmagrc"
    finmagrc.write_text("[demag]\nsolver_type = LU\n")
    monkeypatch.setattr(config_module, "CONFIGURATION_FILES", [str(finmagrc)])

    with pytest.raises(NotImplementedError, match="LU"):
        FKDemag()

    # An explicit kwarg still overrides the config file.
    FKDemag(solver_type="Krylov")

    # No [demag] section (or none at all) falls back to the Krylov default.
    finmagrc.write_text("[other]\nkey = value\n")
    FKDemag()


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
