"""Direct DOLFINx DMI port (Task 13; SR1 P5.2 minimal-diff accounting).

Validates the ported ``finmag.energies.dmi.DMI`` against:

- an analytic zero for uniform ``m`` (both bulk and interfacial forms have no
  gradient to act on);
- an *exact* (machine-precision) chirality/sign pin using the transcribed
  legacy ``times_curl`` witness field ``m = (-y/2, x/2, c)`` (from
  ``finmag.tests.test_dmi_terms.test_dmi_with_analytical_solution``), where
  ``m . curl(m) = c`` exactly for any CG1 interpolant (the field is affine,
  so gradients are exact);
- an *exact* chirality identity for a genuine sinusoidal helix
  ``m = (0, cos(kx), sin(kx))``: replacing ``k`` by ``-k`` only negates the
  ``z``-component's nodal values (the ``y``-component is identical, since
  ``cos`` is even), and algebraically (not just for the true continuum field,
  but for *any* piecewise-linear interpolant sharing those nodal values) that
  transform exactly negates ``m . curl(m)`` when ``m`` only depends on ``x``.
  This is confirmed numerically to double-precision (``E(k) + E(-k) == 0.0``
  exactly), giving a genuine "helix of wavevector q" sign/magnitude pin
  without the discretisation error a direct comparison to the analytic
  continuum value ``E = -D*q*V`` would otherwise carry;
- exact 1D/2D ``unit_length ** (dim - 1)`` scaling checks using affine
  fields chosen so only the derivatives the reduced ``times_curl`` forms keep
  are nonzero, PLUS the master's own physical-invariance check (below) that
  additionally rescales the mesh geometry itself, not just the
  ``unit_length`` argument on a fixed mesh;
- an exact interfacial-DMI sign/magnitude pin using an affine ``m_z`` ramp;
- coordinate-ordered legacy oracle fixture comparisons (bulk 3D and
  interfacial, field + energy) against
  ``src/finmag/tests/fixtures/dmi_oracle.json``, regenerated by
  ``src/finmag/tests/fixtures/gen_dmi_oracle.py``;
- dmi_type dispatch, including the by-name deferral of the undocumented
  legacy ``'D2D'`` variant and unsupported strings;
- support for spatially varying ``D`` (Task 16: callable/Field/Function,
  placed in DG0), with by-name deferral kept only for legacy string
  Expressions and every non-``box-assemble`` method (matching the Task 5
  energy foundation exactly);
- ``sim_with(D=...)`` construction.

MASTER -> PORT MAPPING (git ``b5015c5a``; every master DMI test function
across all 3 ancestor files accounted for so a reviewer can check off each
one):

``src/finmag/energies/dmi_test.py`` (1 test function):
  - test_dmi_field -> DEFERRED. Compares three assembly *methods*
    (box-assemble / box-matrix-numpy / box-matrix-petsc) for numerical
    equivalence. Only ``box-assemble`` is ported; the other two remain
    unimplemented and raise ``NotImplementedError`` by name (matching the
    Task 5 ``Exchange`` precedent), covered-elsewhere by this file's
    ``test_deferred_dmi_methods_are_rejected_precisely[box-matrix-numpy]``
    / ``[box-matrix-petsc]``. Nothing to restore: there is no second
    DOLFINx DMI implementation to compare ``box-assemble`` against yet.

``src/finmag/tests/test_dmi.py`` (4 test functions):
  - test_dmi_uses_unit_length_2dmesh -> GENUINE GAP, RESTORED below as
    ``test_dmi_energy_is_unit_length_invariant_across_rescaled_meshes``.
    Unlike the fixed-mesh ``unit_length ** (dim-1)`` formula checks above
    (which vary only the ``unit_length`` Python argument on one fixed
    mesh), master's test builds THREE differently-scaled meshes
    representing the same physical helical state in different unit
    systems and requires the energies to agree -- exercising the
    interaction between mesh geometry, ``grad``, and the
    ``unit_length``/``dmi_factor`` scaling that a fixed-mesh check cannot
    see. Master's tolerance (``rel_diff < 1e-13``) kept verbatim and
    passes (measured ~2.2e-14 and ~3.2e-14, see below).
  - test_interaction_accepts_name -> covered-elsewhere (stronger): this
    file's ``test_sim_with_dmi_builds_and_computes`` asserts
    ``dmi.name == "DMI"`` exactly, a strict superset of master's mere
    ``hasattr(dmi, 'name')``.
  - test_dmi_pbc2d -> DEFERRED. Already ``@pytest.mark.xfail(reason=
    "unfixed bug")`` in master itself ("We dont use PBC at the moment").
    Periodic boundary conditions are deferred by name at the
    ``Simulation`` level repo-wide (``finmag/sim/sim.py``:
    ``if pbc is not None: _deferred("pbc", ...)``), not a DMI-specific
    gap; nothing DMI-specific to restore.
  - test_dmi_pbc2d_1D -> DEFERRED for the same repo-wide PBC reason
    (``Simulation(..., pbc='2d')`` raises ``NotImplementedError`` by
    name); this test also relies on ``sim.relax(...)``/domain-wall
    dynamics, out of scope for a DMI energy-class port regardless.

``src/finmag/tests/test_dmi_terms.py`` (unconditionally skipped/dead IN
MASTER ITSELF -- reason given there: "Not sure if we even use dmi_term3d
anymore"; every test in this file references ``dmi_term3d`` /
``dmi_term2d`` / ``dmi_term3d_dolfin``, which are not even imported in
master's own file -- the import line is commented out -- and do not exist
anywhere in ``finmag.energies.dmi`` in master OR the port):
  - compare_dmi_term3d_with_dolfin, compare_dmi_term2d_with_dolfin -> not
    tests (no ``test_`` prefix); helpers only called from the skipped
    tests below.
  - test_dmi_term2d -> vestigial/dead in master itself; nothing real to
    restore (``dmi_term2d`` does not exist in either tree).
  - test_dmi_with_analytical_solution -> covered-elsewhere & IMPROVED:
    its physics content (``m = (-y/2, x/2, c)`` => ``curl(m) = (0,0,1)``
    => ``m . curl(m) = c`` => ``E = c`` for a unit-volume cube) is
    transcribed AND ACTUALLY ENABLED (not skipped) as this file's
    ``test_bulk_dmi_affine_twist_field_matches_transcribed_times_curl_
    exactly``, at master's own tolerances (``rel=1e-13``, tighter than
    master's ``eps=1e-13``/``1e-12`` absolute checks).
  - test_dmi_term3d -> vestigial/dead in master itself; nothing real to
    restore (``dmi_term3d`` does not exist in either tree).
  - test_can_post_process_form -> vestigial/dead in master itself; tests
    an internal Jacobian-assembly pattern (``dmi_term3d`` + ``derivative``
    + ``PETScMatrix``) not exposed by the current (or master's own) public
    API.

[Claude Sonnet 5]
"""

import json
import os

import numpy as np
import pytest
from dolfinx import fem, mesh
from mpi4py import MPI

from finmag.energies import DMI
from finmag.field import Field
from finmag.sim.sim import Simulation, sim_with

_FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "dmi_oracle.json")
ORACLE = json.load(open(_FIXTURE))
CASES = ORACLE["cases"]


def _cube(cells=2, dim=3):
    if dim == 1:
        return mesh.create_interval(MPI.COMM_WORLD, cells, [0.0, 2.0])
    if dim == 2:
        return mesh.create_unit_square(MPI.COMM_WORLD, cells, cells)
    return mesh.create_unit_cube(MPI.COMM_WORLD, cells, cells, cells)


def _fields(domain, m_callable_or_value, Ms=8.0e5):
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    return Field(S3, m_callable_or_value, name="m"), Field(DG, Ms, name="Ms")


# --------------------------------------------------------------------------
# import boundary / method / dmi_type validation
# --------------------------------------------------------------------------

def test_dmi_export_does_not_load_legacy_dolfin():
    import sys

    assert DMI.__module__ == "finmag.energies.dmi"
    assert "dolfin" not in sys.modules


@pytest.mark.parametrize(
    "method", ("box-matrix-numpy", "box-matrix-petsc", "project", "direct")
)
def test_deferred_dmi_methods_are_rejected_precisely(method):
    with pytest.raises(NotImplementedError, match="not yet ported"):
        DMI(1e-3, method=method)


def test_unknown_dmi_method_is_not_silently_mapped():
    with pytest.raises(ValueError, match="unsupported energy method"):
        DMI(1e-3, method="mystery")


def test_unsupported_dmi_type_raises_precisely():
    with pytest.raises(ValueError, match="unsupported dmi_type"):
        DMI(1e-3, dmi_type="bogus")


def test_d2d_dmi_type_is_deferred_by_name():
    """The undocumented legacy ``'D2D'`` variant is not ported this slice;
    every other legacy option keeps working."""
    with pytest.raises(NotImplementedError, match="D2D"):
        DMI(1e-3, dmi_type="D2D")


def test_spatially_varying_d_is_supported_string_expression_deferred():
    """Task 16: spatially varying D (callable/Field/Function, placed in DG0) is
    now supported; only legacy string Expressions remain deferred by name."""
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("DG", 0))
    spatial = Field(scalar_space, 1.0)
    Ms = Field(scalar_space, 8.0e5)
    m = Field(fem.functionspace(domain, ("Lagrange", 1, (3,))), (0.0, 0.0, 1.0))

    for value in (spatial, lambda x: 1.0e-3 + x[0]):
        dmi = DMI(value)
        dmi.setup(m, Ms, unit_length=1e-9)
        assert np.all(np.isfinite(dmi.compute_field()))

    with pytest.raises(NotImplementedError, match="string Expression"):
        DMI("x[0]")


def test_dmi_requires_three_component_field():
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("Lagrange", 1))
    m = Field(scalar_space, 1.0)
    Ms = Field(fem.functionspace(domain, ("DG", 0)), 8.0e5)
    with pytest.raises(ValueError, match="three-component"):
        DMI(1e-3).setup(m, Ms)


# --------------------------------------------------------------------------
# analytic zero for uniform m
# --------------------------------------------------------------------------

@pytest.mark.parametrize("dmi_type", ("auto", "1d", "2d", "3d", "interfacial"))
def test_uniform_m_gives_zero_dmi_energy(dmi_type):
    """Uniform ``m`` has zero gradient everywhere, so both the bulk
    (``m . curl(m)``) and interfacial energy *densities* vanish identically
    and the total energy is exactly zero.

    The box-assembled *field* is a different story: ``compute_field()`` is
    the weak-form derivative ``d/dm [D m.curl(m)] = D(v.curl(m) + m.curl(v))``
    for test function ``v``; even when ``curl(m) == 0`` the second term
    ``D m.curl(v)`` need not vanish, since it depends on the *test* function's
    curl, not ``m``'s. This is not a discretisation artefact of the port: it
    is the same well-known physical boundary/edge-canting contribution DMI
    produces at a free surface even for otherwise-uniform magnetisation, and
    follows from the identical UFL derivative the legacy class also uses. It
    is exercised only for energy here; see the chirality/oracle tests below
    for field-level checks."""
    dim = {"1d": 1}.get(dmi_type, 3)
    domain = _cube(dim=dim if dim in (1, 2, 3) else 3)
    m, Ms = _fields(domain, (0.6, 0.8, 0.0))
    dmi = DMI(5e-3, dmi_type=dmi_type)
    dmi.setup(m, Ms, unit_length=1.0e-9)
    assert dmi.compute_energy() == pytest.approx(0.0, abs=1e-25)


# --------------------------------------------------------------------------
# exact chirality / sign pins (bulk)
# --------------------------------------------------------------------------

def test_bulk_dmi_affine_twist_field_matches_transcribed_times_curl_exactly():
    """Transcribed from ``finmag.tests.test_dmi_terms.
    test_dmi_term3d_matches_analytical_solution``: for
    ``m = (-y/2, x/2, c)``, ``curl(m) = (0, 0, 1)`` so ``m . curl(m) = c``
    everywhere, exactly (the field is affine, so CG1 captures it exactly)."""
    domain = mesh.create_unit_cube(MPI.COMM_WORLD, 4, 4, 4)
    c = 1.0

    def m_expr(x):
        return np.vstack((-0.5 * x[1], 0.5 * x[0], np.full(x.shape[1], c)))

    m, Ms = _fields(domain, m_expr)
    dmi = DMI(1.0, dmi_type="auto")
    dmi.setup(m, Ms, unit_length=1.0)
    # Volume of the unit cube is 1, so E = D * c * V = c.
    assert dmi.compute_energy() == pytest.approx(c, rel=1e-13)


def test_bulk_dmi_chirality_sign_flips_with_handedness():
    domain = mesh.create_unit_cube(MPI.COMM_WORLD, 4, 4, 4)
    D = 5.0e-3
    c = 2.0

    def twist(sign):
        def f(x):
            return np.vstack(
                (-sign * 0.5 * x[1], sign * 0.5 * x[0], np.full(x.shape[1], c))
            )

        return f

    m_right, Ms = _fields(domain, twist(1.0))
    m_left, _ = _fields(domain, twist(-1.0))

    right = DMI(D, dmi_type="auto")
    right.setup(m_right, Ms, unit_length=1.0)
    left = DMI(D, dmi_type="auto")
    left.setup(m_left, Ms, unit_length=1.0)

    assert right.compute_energy() == pytest.approx(D * c, rel=1e-13)
    assert left.compute_energy() == pytest.approx(-D * c, rel=1e-13)
    assert right.compute_energy() == pytest.approx(-left.compute_energy(), rel=1e-13)


def test_bulk_dmi_helix_chirality_is_an_exact_sign_identity():
    """A genuine sinusoidal helix ``m = (0, cos(kx), sin(kx))``: negating
    ``k`` keeps the ``y``-component's nodal values identical (``cos`` is
    even) and exactly negates the ``z``-component's nodal values (``sin`` is
    odd). Algebraically, for a field depending only on ``x`` with a zero
    ``x``-component, that nodal transform exactly negates ``m . curl(m)`` --
    an identity of the two FEM functions themselves, not merely of the
    continuum limit, so it holds to machine precision regardless of the
    (mesh-dependent) discretisation error each side carries individually."""
    domain = mesh.create_unit_cube(MPI.COMM_WORLD, 3, 3, 3)
    k = 3.0

    def helix(sign):
        def f(x):
            return np.vstack(
                (np.zeros(x.shape[1]), np.cos(sign * k * x[0]),
                 np.sin(sign * k * x[0]))
            )

        return f

    m_pos, Ms = _fields(domain, helix(1.0))
    m_neg, _ = _fields(domain, helix(-1.0))

    pos = DMI(5.0e-3, dmi_type="auto")
    pos.setup(m_pos, Ms, unit_length=1.0)
    neg = DMI(5.0e-3, dmi_type="auto")
    neg.setup(m_neg, Ms, unit_length=1.0)

    E_pos = pos.compute_energy()
    E_neg = neg.compute_energy()
    assert E_pos != pytest.approx(0.0)
    assert E_pos + E_neg == pytest.approx(0.0, abs=1e-18)
    assert E_pos == pytest.approx(-E_neg, rel=1e-12)


# --------------------------------------------------------------------------
# exact 1D / 2D scaling checks
# --------------------------------------------------------------------------

@pytest.mark.parametrize("unit_length", (1.0, 2.0, 5.0))
def test_1d_dmi_energy_is_independent_of_unit_length(unit_length):
    """``dim - 1 == 0`` for a 1D mesh, so the legacy
    ``unit_length ** (dim - 1)`` convention predicts no unit_length
    dependence at all -- an exact, easily overlooked edge case."""
    domain = mesh.create_interval(MPI.COMM_WORLD, 4, [0.0, 2.0])
    b, c = 0.3, 0.7

    def m_expr(x):
        return np.vstack(
            (np.zeros(x.shape[1]), np.full(x.shape[1], b), c * x[0])
        )

    m, Ms = _fields(domain, m_expr)
    dmi = DMI(5.0e-3, dmi_type="1d")
    dmi.setup(m, Ms, unit_length=unit_length)
    expected = 5.0e-3 * (-b * c) * 2.0  # mesh length 2.0, unit_length**0 == 1
    assert dmi.compute_energy() == pytest.approx(expected, rel=1e-12)


@pytest.mark.parametrize("unit_length", (1.0, 3.0))
def test_2d_dmi_energy_scales_linearly_with_unit_length(unit_length):
    domain = mesh.create_unit_square(MPI.COMM_WORLD, 3, 3)
    p, q, c, d = 0.4, 0.5, 0.6, 0.9

    def m_expr(x):
        return np.vstack(
            (np.full(x.shape[1], p), np.full(x.shape[1], q), c * x[0] + d * x[1])
        )

    m, Ms = _fields(domain, m_expr)
    dmi = DMI(5.0e-3, dmi_type="2d")
    dmi.setup(m, Ms, unit_length=unit_length)
    expected = 5.0e-3 * (p * d - q * c) * unit_length  # Area 1, dim - 1 == 1
    assert dmi.compute_energy() == pytest.approx(expected, rel=1e-12)


def test_dmi_energy_is_unit_length_invariant_across_rescaled_meshes():
    """Restored from ``finmag.tests.test_dmi.
    test_dmi_uses_unit_length_2dmesh`` (SR1 P5.2 mapping-header accounting:
    genuinely-dropped master coverage). Unlike the fixed-mesh scaling checks
    above -- which hold the mesh geometry fixed and vary only the
    ``unit_length`` *argument* to confirm the ``unit_length ** (dim - 1)``
    formula algebraically -- this test builds THREE actually differently
    -scaled 2D meshes representing the *same* physical helical state in SI
    units, in units of ``1e-4``, and in nanometres, and requires the
    computed DMI energies to agree. This additionally exercises the
    interaction between real mesh-coordinate rescaling, ``grad``, and the
    ``unit_length``/``dmi_factor`` convention, which the fixed-mesh checks
    cannot see. Master's own tolerance (``rel_diff < 1e-13``) is kept
    verbatim and passes under DOLFINx (measured ~2.2e-14 / ~3.2e-14)."""
    A = 8.78e-12  # J/m
    D = 1.58e-3  # J/m^2
    Ms = 3.84e5  # A/m

    energies = []
    for unit_length in (1.0, 1e-4, 1e-9):
        radius = 200e-9 / unit_length
        maxh = 5e-9 / unit_length
        helical_period = (4.0 * np.pi * A / D) / unit_length
        k = 2.0 * np.pi / helical_period
        nx = ny = int(round(radius / maxh))

        domain = mesh.create_rectangle(
            MPI.COMM_WORLD, [(0.0, 0.0), (radius, radius)], [nx, ny])

        def m_expr(x, k=k):
            return np.vstack(
                (np.zeros(x.shape[1]), np.cos(k * x[0]), np.sin(k * x[0])))

        m, Ms_field = _fields(domain, m_expr, Ms=Ms)
        dmi = DMI(D)
        dmi.setup(m, Ms_field, unit_length=unit_length)
        energies.append(dmi.compute_energy())

    rel_diff_01 = abs(energies[0] - energies[1]) / abs(energies[1])
    rel_diff_02 = abs(energies[0] - energies[2]) / abs(energies[2])
    assert rel_diff_01 < 1e-13
    assert rel_diff_02 < 1e-13


# --------------------------------------------------------------------------
# interfacial exact sign/magnitude pin
# --------------------------------------------------------------------------

def test_interfacial_dmi_affine_ramp_matches_legacy_form_exactly():
    """Transcribed from ``finmag.energies.dmi.DMI_interfacial``: for
    ``mx = a``, ``my = b`` constant and ``mz = c*x + e*y``, the bracket
    reduces exactly to ``a*c + b*e`` (every ``mz``-multiplied derivative
    vanishes since ``mx``/``my`` are constant)."""
    domain = mesh.create_unit_cube(MPI.COMM_WORLD, 3, 3, 3)
    a, b, c, e = 0.2, 0.3, 0.5, 0.8
    D = 5.0e-3

    def m_expr(sign):
        def f(x):
            return np.vstack(
                (np.full(x.shape[1], a), np.full(x.shape[1], b),
                 sign * (c * x[0] + e * x[1]))
            )

        return f

    m_pos, Ms = _fields(domain, m_expr(1.0))
    m_neg, _ = _fields(domain, m_expr(-1.0))

    pos = DMI(D, dmi_type="interfacial")
    pos.setup(m_pos, Ms, unit_length=1.0)
    neg = DMI(D, dmi_type="interfacial")
    neg.setup(m_neg, Ms, unit_length=1.0)

    expected = D * (a * c + b * e)
    assert pos.compute_energy() == pytest.approx(expected, rel=1e-12)
    assert neg.compute_energy() == pytest.approx(-expected, rel=1e-12)


# --------------------------------------------------------------------------
# coordinate-ordered legacy oracle comparisons
# --------------------------------------------------------------------------

def _scalar_quantity(case, name):
    for q in case["scalar_quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _quantity(case, name):
    for q in case["quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _oracle_box_mesh():
    extent = 0.7
    return mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (extent, extent, extent)],
        [4, 4, 4], mesh.CellType.tetrahedron)


def _oracle_m():
    def f(x):
        return np.vstack(
            (np.full(x.shape[1], 0.6), 0.8 * np.cos(2.0 * np.pi * x[0]),
             0.8 * np.sin(2.0 * np.pi * x[0]))
        )

    return f


def _oracle_compare(case_name, dmi_type):
    case = CASES[case_name]
    domain = _oracle_box_mesh()
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    m = Field(S3, _oracle_m(), name="m")
    Ms = Field(DG, 8.0e5, name="Ms")

    dmi = DMI(5.0e-3, dmi_type=dmi_type)
    dmi.setup(m, Ms, unit_length=1e-9)
    E = dmi.compute_energy()
    # Task 31: component-blocked field -> owned-vertex per-node rows, sorted
    # against the matching owned-vertex coordinates.
    H = dmi.compute_field().reshape((3, -1)).T
    coords, _ = m.coords_and_values()
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    coords_s, H_s = coords[order], H[order]

    ref_coords = np.asarray(case["coordinates"]["values"])
    energy_q = _scalar_quantity(case, "energy")
    H_q = _quantity(case, "H_vertex")
    m_q = _quantity(case, "m_vertex")

    assert coords_s.shape == ref_coords.shape
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    # Sanity-check the input magnetisation matches the oracle's own recorded
    # nodal m before comparing the derived field/energy (Finding: a fixture
    # only proves the DMI physics is faithfully transcribed if the ``m`` that
    # produced it is confirmed identical, not merely assumed so).
    m_coords, m_values = m.coords_and_values()
    m_order = np.lexsort((m_coords[:, 2], m_coords[:, 1], m_coords[:, 0]))
    np.testing.assert_allclose(
        m_values[m_order], np.asarray(m_q["values"]),
        atol=m_q["tolerances"]["absolute"], rtol=m_q["tolerances"]["relative"])

    e_tol = energy_q["tolerances"]
    np.testing.assert_allclose(
        E, energy_q["value"], atol=e_tol["absolute"], rtol=e_tol["relative"])
    H_tol = H_q["tolerances"]
    np.testing.assert_allclose(
        H_s, np.asarray(H_q["values"]), atol=H_tol["absolute"],
        rtol=H_tol["relative"])


def test_oracle_bulk_3d_field_energy():
    _oracle_compare("bulk_3d", "auto")


def test_oracle_interfacial_field_energy():
    _oracle_compare("interfacial", "interfacial")


# --------------------------------------------------------------------------
# sim_with integration
# --------------------------------------------------------------------------

def test_sim_with_dmi_builds_and_computes():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = sim_with(
        box, Ms=8.6e5, m_init=(1.0, 0.0, 0.0), unit_length=1e-9,
        D=5e-3, demag_solver=None)
    assert sim.has_interaction("DMI")
    dmi = sim.get_interaction("DMI")
    assert dmi.name == "DMI"
    assert np.isfinite(dmi.compute_energy())
    assert np.all(np.isfinite(dmi.compute_field()))


def test_dmi_added_to_simulation_directly():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="dmi_direct")
    sim.set_m((0.0, 0.0, 1.0))
    sim.add(DMI(5e-3))
    assert sim.has_interaction("DMI")
    assert np.isfinite(sim.total_energy())
