"""Direct DOLFINx cubic-anisotropy port (Task 14).

Validates the ported ``finmag.energies.cubic_anisotropy.CubicAnisotropy``
against:

- the legacy module's own analytic reference values (transcribed from
  ``finmag.energies.cubic_anisotropy_test.py::test_cubic_anisotropy_energy``:
  same ``K1``/``K2``/``K3``/``u1``/``u2`` constants, same uniform
  ``m = (0, 0, 1)``);
- cubic-symmetry easy/hard-axis energy ordering for the standard orthonormal
  crystallographic axes (``K1 > 0``): ``E([100]) == 0``,
  ``E([110]) - E([100]) == K1/4 * V``, ``E([111]) - E([100]) == K1/3 * V``
  (derived from the transcribed energy-density form itself, not assumed);
- the ``K2``/``K3`` contributions in isolation (the other two constants set
  to zero);
- axis-handling behavior transcribed exactly from the legacy class: ``u3 =
  u1 x u2``, and ``u1``/``u2`` are used *as given* -- neither renormalised
  nor checked for orthogonality (matching
  ``dev/dolfinx/prototype.py::cubic_anisotropy_energy``'s documented
  investigation and the legacy class's own non-unit,
  not-quite-orthogonal ``cubic_anisotropy_test.py`` axes);
- by-name deferral of spatially varying ``K1``/``K2``/``K3``/``u1``/``u2``
  and of ``compute_field()`` under the legacy-default ``assemble=False``
  (the unported native/direct field path);
- a coordinate-ordered legacy oracle fixture comparison (field + energy)
  against ``src/finmag/tests/fixtures/cubic_anisotropy_oracle.json``,
  regenerated by
  ``src/finmag/tests/fixtures/gen_cubic_anisotropy_oracle.py``;
- ``Simulation``/``sim.add(...)`` integration, including a dynamics effect.

[Claude Sonnet 5]
"""

import json
import os

import numpy as np
import pytest
from dolfinx import fem, mesh
from mpi4py import MPI

from finmag.energies import CubicAnisotropy
from finmag.field import Field
from finmag.sim.sim import Simulation

_FIXTURE = os.path.join(
    os.path.dirname(__file__), "fixtures", "cubic_anisotropy_oracle.json")
ORACLE = json.load(open(_FIXTURE))
CASE = ORACLE["cases"]["cubic_3d"]

# Same constants/axes as finmag.energies.cubic_anisotropy_test.py.
UNIT_LENGTH = 1e-9
Ms_LEGACY = 876626
K1_LEGACY = -8608726
K2_LEGACY = -13744132
K3_LEGACY = 1100269
U1_LEGACY = (0, -0.7071, 0.7071)
U2_LEGACY = (0, 0.7071, 0.7071)


def _cube(cells=2):
    return mesh.create_unit_cube(MPI.COMM_WORLD, cells, cells, cells)


def _fields(domain, m_value, Ms=8.0e5):
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    return Field(S3, m_value, name="m"), Field(DG, Ms, name="Ms")


def _domain_volume(domain):
    import ufl

    local = fem.assemble_scalar(fem.form(fem.Constant(domain, 1.0) * ufl.dx))
    return domain.comm.allreduce(local, op=MPI.SUM)


# --------------------------------------------------------------------------
# import boundary
# --------------------------------------------------------------------------

def test_cubic_anisotropy_export_does_not_load_legacy_dolfin():
    import sys

    assert CubicAnisotropy.__module__ == "finmag.energies.cubic_anisotropy"
    assert "dolfin" not in sys.modules


def test_cubic_anisotropy_requires_three_component_field():
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("Lagrange", 1))
    m = Field(scalar_space, 1.0)
    Ms = Field(fem.functionspace(domain, ("DG", 0)), 8.0e5)
    with pytest.raises(ValueError, match="three-component"):
        CubicAnisotropy((1, 0, 0), (0, 1, 0), 1e4, assemble=True).setup(m, Ms)


# --------------------------------------------------------------------------
# legacy analytic reference values
# (finmag.energies.cubic_anisotropy_test.py::test_cubic_anisotropy_energy)
# --------------------------------------------------------------------------

def _legacy_reference_energy(m_vec):
    u1, u2 = np.asarray(U1_LEGACY), np.asarray(U2_LEGACY)
    u3 = np.cross(u1, u2)
    a = np.dot(u1, m_vec)
    b = np.dot(u2, m_vec)
    c = np.dot(u3, m_vec)
    energy = K1_LEGACY * (a**2 * b**2 + a**2 * c**2 + b**2 * c**2)
    energy += K2_LEGACY * (a**2 * b**2 * c**2)
    energy += K3_LEGACY * (a**4 * b**4 + a**4 * c**4 + b**4 * c**4)
    return energy


def test_legacy_analytic_reference_energy_matches_exactly():
    domain = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (1.0, 1.0, 40.0)], [1, 1, 40],
        mesh.CellType.tetrahedron)
    volume = _domain_volume(domain) * UNIT_LENGTH**3

    m, Ms = _fields(domain, (0.0, 0.0, 1.0), Ms=Ms_LEGACY)
    ca = CubicAnisotropy(U1_LEGACY, U2_LEGACY, K1_LEGACY, K2_LEGACY, K3_LEGACY)
    ca.setup(m, Ms, UNIT_LENGTH)

    energy = ca.compute_energy()
    energy_expected = _legacy_reference_energy((0.0, 0.0, 1.0)) * volume

    rel_diff = abs(energy - energy_expected) / abs(energy_expected)
    assert rel_diff < 1e-10


# --------------------------------------------------------------------------
# cubic-symmetry easy/hard-axis energy ordering
# --------------------------------------------------------------------------

def _energy_for_direction(m_direction, K1=1.0e4):
    domain = _cube()
    m, Ms = _fields(domain, tuple(m_direction))
    ca = CubicAnisotropy((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), K1, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)
    return ca.compute_energy()


def test_cubic_symmetry_easy_hard_axis_ordering_for_positive_k1():
    """For K1 > 0 and the standard orthonormal cubic axes, <100> is the easy
    direction (E == 0) and <111> is the hardest, with exact ratios derivable
    from the transcribed energy density: with a = m . [100] etc, E([100]) has
    (a,b,c) = (1,0,0) so every product a^2 b^2 etc vanishes; E([110]) has
    a=b=1/sqrt(2), c=0, giving a^2 b^2 = 1/4; E([111]) has a=b=c=1/sqrt(3),
    giving three terms of 1/9 each, summing to 1/3."""
    K1 = 1.0e4
    e100 = _energy_for_direction((1.0, 0.0, 0.0), K1)
    e110 = _energy_for_direction((1.0 / np.sqrt(2), 1.0 / np.sqrt(2), 0.0), K1)
    e111 = _energy_for_direction(
        (1.0 / np.sqrt(3), 1.0 / np.sqrt(3), 1.0 / np.sqrt(3)), K1)

    assert e100 == pytest.approx(0.0, abs=1e-9)
    assert (e110 - e100) == pytest.approx(K1 / 4.0, rel=1e-10)
    assert (e111 - e100) == pytest.approx(K1 / 3.0, rel=1e-10)
    # <100> easy, <110> intermediate, <111> hard.
    assert e100 < e110 < e111


# --------------------------------------------------------------------------
# K2 / K3 contributions in isolation
# --------------------------------------------------------------------------

def test_k2_contribution_in_isolation():
    """With K1 = K3 = 0, E = K2 * a^2 b^2 c^2 exactly."""
    domain = _cube()
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    u1, u2 = (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)
    K2 = 3.0e4

    m, Ms = _fields(domain, m_vec)
    ca = CubicAnisotropy(u1, u2, K1=0.0, K2=K2, K3=0.0, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    u3 = np.cross(u1, u2)
    a, b, c = (np.dot(ax, m_vec) for ax in (u1, u2, u3))
    expected = K2 * (a**2 * b**2 * c**2)
    assert ca.compute_energy() == pytest.approx(expected, rel=1e-10)


def test_k3_contribution_in_isolation():
    """With K1 = K2 = 0, E = K3 * (a^4 b^4 + b^4 c^4 + c^4 a^4) exactly."""
    domain = _cube()
    m_vec = (0.2, 0.5, np.sqrt(1.0 - 0.2**2 - 0.5**2))
    u1, u2 = (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)
    K3 = 7.0e2

    m, Ms = _fields(domain, m_vec)
    ca = CubicAnisotropy(u1, u2, K1=0.0, K2=0.0, K3=K3, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    u3 = np.cross(u1, u2)
    a, b, c = (np.dot(ax, m_vec) for ax in (u1, u2, u3))
    expected = K3 * (a**4 * b**4 + b**4 * c**4 + c**4 * a**4)
    assert ca.compute_energy() == pytest.approx(expected, rel=1e-10)


# --------------------------------------------------------------------------
# axis handling: u3 = u1 x u2, non-orthogonal/non-unit axes silently accepted
# --------------------------------------------------------------------------

def test_u3_is_cross_product_of_u1_and_u2():
    domain = _cube()
    m, Ms = _fields(domain, (0.3, 0.4, np.sqrt(1 - 0.3**2 - 0.4**2)))
    u1, u2 = (1.0, 2.0, 0.0), (0.0, 1.0, 3.0)
    ca = CubicAnisotropy(u1, u2, K1=1.0e4, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)
    np.testing.assert_allclose(ca.u3_value, np.cross(u1, u2))


def test_non_orthogonal_non_unit_axes_are_silently_accepted():
    """Legacy ``CubicAnisotropy`` performs no normalisation and no
    orthogonality check on ``u1``/``u2`` -- it documents them as "should be
    unit vectors" but does not enforce it (see
    ``dev/dolfinx/prototype.py::cubic_anisotropy_energy``'s investigation
    note, and the legacy module's own ``cubic_anisotropy_test.py``, whose
    axes ``u1=(0,-0.7071,0.7071)``/``u2=(0,0.7071,0.7071)`` are not exactly
    unit vectors: ``0.7071**2 * 2 == 0.99980082 != 1``). This port preserves
    that behaviour exactly rather than raising or silently renormalising."""
    u1 = np.array((1.0, 0.3, 0.0))  # not unit length
    u2 = np.array((0.2, 1.0, 0.1))  # not orthogonal to u1, not unit length
    assert not np.isclose(np.linalg.norm(u1), 1.0)
    assert not np.isclose(np.dot(u1, u2), 0.0)

    domain = _cube()
    m, Ms = _fields(domain, (0.3, 0.4, np.sqrt(1 - 0.3**2 - 0.4**2)))
    ca = CubicAnisotropy(u1, u2, K1=1.0e4, K2=5.0e3, K3=1.0e2, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    np.testing.assert_allclose(ca.u1_value, u1)
    np.testing.assert_allclose(ca.u2_value, u2)
    np.testing.assert_allclose(ca.u3_value, np.cross(u1, u2))
    assert np.isfinite(ca.compute_energy())


def test_axis_must_be_three_component_vector():
    with pytest.raises(ValueError, match="three-component vector"):
        CubicAnisotropy((1.0, 0.0), (0.0, 1.0, 0.0), 1.0e4)
    with pytest.raises(ValueError, match="three-component vector"):
        CubicAnisotropy((1.0, 0.0, 0.0), (0.0, 1.0, 0.0, 0.0), 1.0e4)


# --------------------------------------------------------------------------
# by-name deferrals
# --------------------------------------------------------------------------

def test_spatially_varying_k1_k2_k3_are_deferred_by_name():
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("DG", 0))
    spatial = Field(scalar_space, 1.0)

    for name, kwargs in (
        ("K1", dict(K1=spatial)),
        ("K2", dict(K1=1.0, K2=spatial)),
        ("K3", dict(K1=1.0, K3=spatial)),
    ):
        with pytest.raises(NotImplementedError, match="spatially varying"):
            CubicAnisotropy((1, 0, 0), (0, 1, 0), **kwargs)

    with pytest.raises(NotImplementedError, match="spatially varying K1"):
        CubicAnisotropy((1, 0, 0), (0, 1, 0), "1.0 + x[0]")
    with pytest.raises(NotImplementedError, match="spatially varying K1"):
        CubicAnisotropy((1, 0, 0), (0, 1, 0), lambda x: 1.0 + x[0])


def test_spatially_varying_axes_are_deferred_by_name():
    domain = _cube()
    vector_space = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    spatial_axis = Field(vector_space, (1.0, 0.0, 0.0))

    with pytest.raises(NotImplementedError, match="spatially varying u1"):
        CubicAnisotropy(spatial_axis, (0, 1, 0), 1.0e4)
    with pytest.raises(NotImplementedError, match="spatially varying u2"):
        CubicAnisotropy((1, 0, 0), spatial_axis, 1.0e4)
    with pytest.raises(NotImplementedError, match="spatially varying u1"):
        CubicAnisotropy(lambda x: x, (0, 1, 0), 1.0e4)
    with pytest.raises(NotImplementedError, match="spatially varying u1"):
        CubicAnisotropy(("1.0", "0.0", "0.0"), (0, 1, 0), 1.0e4)


def test_default_assemble_false_computes_energy_but_defers_field():
    """The legacy default constructor call (``assemble`` left at its default
    ``False``) matches ``cubic_anisotropy_test.py`` exactly and must keep
    working for energy; only the unported native/direct field computation
    raises."""
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0))
    ca = CubicAnisotropy((1, 0, 0), (0, 1, 0), 1.0e4, 2.0e3, 3.0e2)
    ca.setup(m, Ms, unit_length=1.0)

    assert ca.assemble is False
    assert np.isfinite(ca.compute_energy())
    with pytest.raises(NotImplementedError, match="assemble=True"):
        ca.compute_field()


def test_assemble_true_computes_field():
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.3, np.sqrt(1 - 0.09)))
    ca = CubicAnisotropy((1, 0, 0), (0, 1, 0), 1.0e4, 2.0e3, 3.0e2, assemble=True)
    ca.setup(m, Ms, unit_length=1.0)

    assert ca.assemble is True
    field = ca.compute_field()
    assert np.all(np.isfinite(field))
    assert np.max(np.abs(field)) > 0.0


# --------------------------------------------------------------------------
# coordinate-ordered legacy oracle comparison
# --------------------------------------------------------------------------

def _oracle_box_mesh():
    extent = 0.7
    return mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (extent, extent, extent)],
        [4, 4, 4], mesh.CellType.tetrahedron)


def _oracle_m():
    def f(x):
        return np.vstack(
            (np.full(x.shape[1], 0.6), 0.8 * np.cos(2.0 * np.pi * x[0]),
             0.8 * np.sin(2.0 * np.pi * x[0]))
        )

    return f


def test_oracle_cubic_3d_field_energy():
    physical = CASE["physical_parameters"]
    domain = _oracle_box_mesh()
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    m = Field(S3, _oracle_m(), name="m")
    Ms = Field(DG, physical["Ms"]["value"], name="Ms")

    ca = CubicAnisotropy(
        physical["u1"]["value"], physical["u2"]["value"],
        physical["K1"]["value"], physical["K2"]["value"],
        physical["K3"]["value"], assemble=True)
    ca.setup(m, Ms, unit_length=physical["unit_length"]["value"])

    E = ca.compute_energy()
    H = ca.compute_field().reshape(-1, 3)
    coords = S3.tabulate_dof_coordinates()
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    coords_s, H_s = coords[order], H[order]

    ref_coords = np.asarray(CASE["coordinates"]["values"])
    energy_q = CASE["scalar_quantities"][0]
    assert energy_q["name"] == "energy"
    H_q = CASE["quantities"][1]
    assert H_q["name"] == "H_vertex"
    m_q = CASE["quantities"][0]
    assert m_q["name"] == "m_vertex"

    assert coords_s.shape == ref_coords.shape
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    m_coords, m_values = m.coords_and_values()
    m_order = np.lexsort((m_coords[:, 2], m_coords[:, 1], m_coords[:, 0]))
    np.testing.assert_allclose(
        m_values[m_order], np.asarray(m_q["values"]),
        atol=m_q["tolerances"]["absolute"], rtol=m_q["tolerances"]["relative"])

    e_tol = energy_q["tolerances"]
    np.testing.assert_allclose(
        E, energy_q["value"], atol=e_tol["absolute"], rtol=e_tol["relative"])
    H_tol = H_q["tolerances"]
    np.testing.assert_allclose(
        H_s, np.asarray(H_q["values"]), atol=H_tol["absolute"],
        rtol=H_tol["relative"])


# --------------------------------------------------------------------------
# Simulation integration
# --------------------------------------------------------------------------

def test_cubic_anisotropy_added_to_simulation_directly():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="cubic_anis_direct")
    sim.set_m((0.3, 0.4, np.sqrt(1 - 0.09 - 0.16)))
    sim.add(CubicAnisotropy(
        (1, 0, 0), (0, 1, 0), 1.0e4, 2.0e3, 3.0e2, assemble=True))
    assert sim.has_interaction("CubicAnisotropy")
    assert np.isfinite(sim.total_energy())
    assert np.all(np.isfinite(sim.effective_field()))


def test_cubic_anisotropy_default_assemble_defers_effective_field_by_name():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="cubic_anis_default")
    sim.set_m((0.0, 0.0, 1.0))
    sim.add(CubicAnisotropy((1, 0, 0), (0, 1, 0), 1.0e4))
    assert np.isfinite(sim.total_energy())
    with pytest.raises(NotImplementedError, match="assemble=True"):
        sim.effective_field()


def test_cubic_anisotropy_affects_dynamics():
    """A cubic-anisotropy-only simulation, started away from an easy axis,
    must precess/relax under a genuinely nonzero effective field -- i.e. the
    interaction is actually wired into the LLG dynamics, not just present in
    the energy bookkeeping."""
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, 8.6e5, unit_length=1e-9, name="cubic_anis_dynamics")
    # A generic, low-symmetry direction (not aligned with any easy/hard axis
    # of the standard cubic axes below), so the effective field is not
    # parallel to m and the LLG torque m x H_eff is genuinely nonzero.
    m0 = np.array((1.0, 0.3, 0.1))
    m0 /= np.linalg.norm(m0)
    sim.set_m(tuple(m0))
    sim.alpha = 0.5
    sim.add(CubicAnisotropy(
        (1, 0, 0), (0, 1, 0), 1.0e4, assemble=True))

    field0 = sim.effective_field()
    assert np.max(np.abs(field0)) > 0.0

    sim.run_until(1e-9)
    m_after = sim.m.reshape((3, -1)).T[0]
    assert not np.allclose(m_after, m0, atol=1e-6)
