"""Direct DOLFINx ``ThinFilmDemag`` port (Task 19).

``ThinFilmDemag`` is legacy's analytic thin-film demagnetising approximation
(``Hi = -strength_i * m_i`` for a single chosen axis ``i``, ``strength``
defaulting to a box-averaged ``Ms``) -- the last legacy-tested energy class
still importing ``dolfin`` at module scope before this port.

Validates the ported ``finmag.energies.thin_film_demag.ThinFilmDemag``
against:

- the transcribed legacy ``thin_film_demag_test.py`` invariants (name
  attribute, zero field for magnetisation perpendicular to ``direction``, an
  exact analytic field for magnetisation aligned with ``direction``, and a
  slow cross-check against the ported ``FKDemag`` on a thin-film-like bar);
- construction/setup validation consistent with every other ported
  interaction (Field type checks, CG1 requirement, mesh-matching, invalid
  ``direction``);
- the "recomputed fresh on every call" contract (not cached at ``setup``
  time, unlike the documented ``DiscreteTimeZeeman`` legacy defect);
- the explicit ``field_strength`` branch (bypasses the ``Ms``-average
  entirely);
- coordinate-ordered legacy oracle fixture comparisons (both the
  ``field_strength=None``/varying-``Ms`` branch and the explicit-
  ``field_strength`` branch) against
  ``src/finmag/tests/fixtures/thin_film_demag_oracle.json``, regenerated by
  ``src/finmag/tests/fixtures/gen_thin_film_demag_oracle.py``;
- ``Simulation.add()`` integration (legacy never wired this into
  ``sim_with``; it is only ever added directly, exactly as ported here).

[Claude Sonnet 5]
"""

import json
import os

import numpy as np
import pytest
from dolfinx import fem, mesh
from mpi4py import MPI

from finmag.energies import ThinFilmDemag, Demag
from finmag.field import Field
from finmag.sim.sim import Simulation

_FIXTURE = os.path.join(
    os.path.dirname(__file__), "fixtures", "thin_film_demag_oracle.json")
ORACLE = json.load(open(_FIXTURE))
CASES = ORACLE["cases"]

Ms_CONST = 8.6e5


def _cube(cells=2):
    return mesh.create_unit_cube(MPI.COMM_WORLD, cells, cells, cells)


def _fields(domain, m_value, Ms=Ms_CONST):
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    return Field(S3, m_value, name="m"), Field(DG, Ms, name="Ms")


# --------------------------------------------------------------------------
# import boundary / construction
# --------------------------------------------------------------------------

def test_thin_film_demag_export_does_not_load_legacy_dolfin():
    import sys

    assert ThinFilmDemag.__module__ == "finmag.energies.thin_film_demag"
    assert "dolfin" not in sys.modules


def test_interaction_accepts_name():
    """Transcribed from legacy ``test_interaction_accepts_name``."""
    demag = ThinFilmDemag()
    assert hasattr(demag, "name")
    assert demag.name == "ThinFilmDemag"


def test_invalid_direction_raises_value_error():
    with pytest.raises(ValueError, match="direction"):
        ThinFilmDemag(direction="w")


def test_requires_three_component_m_field():
    domain = _cube()
    scalar_space = fem.functionspace(domain, ("Lagrange", 1))
    m = Field(scalar_space, 1.0)
    Ms = Field(fem.functionspace(domain, ("DG", 0)), Ms_CONST)
    with pytest.raises(ValueError, match="three-component"):
        ThinFilmDemag().setup(m, Ms, 1e-9)


def test_requires_field_instances():
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0))
    with pytest.raises(TypeError, match="finmag.Field"):
        ThinFilmDemag().setup(m.as_array(), Ms, 1e-9)
    with pytest.raises(TypeError, match="finmag.Field"):
        ThinFilmDemag().setup(m, Ms.as_array(), 1e-9)


def test_requires_matching_mesh():
    domain_a = _cube()
    domain_b = _cube(cells=3)
    m, _ = _fields(domain_a, (0.0, 0.0, 1.0))
    _, Ms = _fields(domain_b, (0.0, 0.0, 1.0))
    with pytest.raises(ValueError, match="same mesh"):
        ThinFilmDemag().setup(m, Ms, 1e-9)


# --------------------------------------------------------------------------
# transcribed legacy analytic invariants
# --------------------------------------------------------------------------

def _compare_with_expected(H_gen, m_init, atol=0.0, rtol=0.0):
    domain = _cube()
    m, Ms = _fields(domain, m_init)
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)
    H_computed = demag.compute_field()
    H_expected = H_gen(m.as_array())
    np.testing.assert_allclose(H_computed, H_expected, atol=atol, rtol=rtol)


def test_zero_thin_film_demag():
    """Transcribed from legacy ``test_zero_thin_film_demag``: magnetisation
    perpendicular to the (default ``"z"``) direction gives an exactly zero
    field."""
    _compare_with_expected(lambda m: np.zeros_like(m), (1.0, 0.0, 0.0), atol=1e-14)
    _compare_with_expected(
        lambda m: np.zeros_like(m), (1.0 / np.sqrt(2), 1.0 / np.sqrt(2), 0.0),
        atol=1e-14)


def test_thin_film_demag():
    """Transcribed from legacy ``test_thin_film_demag``: magnetisation
    aligned with the direction axis gives ``H == -Ms * m`` exactly."""
    _compare_with_expected(lambda m: -Ms_CONST * m, (0.0, 0.0, 1.0), rtol=1e-14)


@pytest.mark.slow
def test_thin_film_demag_against_real_demag():
    """Transcribed from legacy ``test_thin_film_demag_against_real_demag``: a
    sanity regression against the full ported ``FKDemag`` on a thin-film-like
    bar, not a claim that the thin-film model is exact. Also exercises the
    "recomputed fresh on every call" contract: ``compute_field()`` is called
    again after changing ``m`` in place, and both interactions must reflect
    the new state (neither caches a stale field)."""
    domain = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (500e-9, 500e-9, 1e-9)],
        [50, 50, 1], mesh.CellType.tetrahedron)
    m, Ms = _fields(domain, (0.0, 0.0, 1.0))

    tfdemag = ThinFilmDemag()
    tfdemag.setup(m, Ms, unit_length=1.0)
    H_tfdemag = tfdemag.compute_field().reshape((-1, 3)).mean(axis=0)

    demag = Demag()
    demag.setup(m, Ms, unit_length=1.0)
    H_demag = demag.compute_field().reshape((-1, 3)).mean(axis=0)

    diff = np.abs(H_tfdemag - H_demag) / Ms_CONST
    assert np.allclose(H_tfdemag, H_demag, atol=0.05 * Ms_CONST)  # 5% of Ms
    assert np.all(diff < 0.05)

    m.set((1.0, 0.0, 0.0))
    H_tfdemag = tfdemag.compute_field().reshape((-1, 3)).mean(axis=0)
    H_demag = demag.compute_field().reshape((-1, 3)).mean(axis=0)

    diff = np.abs(H_tfdemag - H_demag) / Ms_CONST
    assert np.allclose(H_tfdemag, H_demag, atol=0.005 * Ms_CONST)  # 0.5% of Ms
    assert np.all(diff < 0.005)


def test_compute_field_is_recomputed_fresh_every_call():
    """Not a legacy-file transcription, but a direct pin of the "not cached"
    contract legacy's own ``compute_field`` relies on (it always reads
    ``self.m.get_numpy_array_debug()`` fresh) -- worth pinning explicitly
    given the documented ``DiscreteTimeZeeman`` legacy caching defect
    elsewhere in this port (see ``zeeman.py``)."""
    domain = _cube()
    m, Ms = _fields(domain, (1.0, 0.0, 0.0))
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)

    first = demag.compute_field()
    np.testing.assert_allclose(first, np.zeros_like(first), atol=1e-14)

    m.set((0.0, 0.0, 1.0))
    second = demag.compute_field()
    expected = -Ms_CONST * m.as_array()
    np.testing.assert_allclose(second, expected, rtol=1e-14)


# --------------------------------------------------------------------------
# field_strength branches
# --------------------------------------------------------------------------

def test_explicit_field_strength_bypasses_ms_average():
    domain = _cube()
    m, Ms = _fields(domain, (1.0, 0.0, 0.0), Ms=1.0e6)
    demag = ThinFilmDemag(direction="x", field_strength=250.0)
    demag.setup(m, Ms, unit_length=1e-9)
    H = demag.compute_field().reshape((-1, 3))
    expected = np.zeros_like(H)
    expected[:, 0] = -250.0 * 1.0
    np.testing.assert_allclose(H, expected, rtol=1e-14)


def test_default_field_strength_is_ms_box_average():
    """``field_strength=None`` (the default) recovers a uniform ``Ms``
    exactly via the box average, matching ``test_thin_film_demag`` above but
    asserting the intermediate ``strength`` explicitly."""
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0), Ms=Ms_CONST)
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)
    np.testing.assert_allclose(demag.strength, Ms_CONST, rtol=1e-10)


def test_compute_energy_is_the_legacy_literal_zero():
    domain = _cube()
    m, Ms = _fields(domain, (0.0, 0.0, 1.0))
    demag = ThinFilmDemag()
    demag.setup(m, Ms, unit_length=1e-9)
    assert demag.compute_field() is not None  # sanity: setup succeeded
    assert demag.compute_energy() == 0


# --------------------------------------------------------------------------
# coordinate-ordered legacy oracle comparisons
# --------------------------------------------------------------------------

def _quantity(case, name):
    for q in case["quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _scalar_quantity(case, name):
    for q in case["scalar_quantities"]:
        if q["name"] == name:
            return q
    raise KeyError(name)


def _oracle_box_mesh():
    extent = 0.7
    return mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (extent, extent, extent)],
        [3, 3, 3], mesh.CellType.tetrahedron)


def _oracle_m():
    def f(x):
        return np.vstack(
            (np.full(x.shape[1], 0.6), 0.8 * np.cos(2.0 * np.pi * x[0]),
             0.8 * np.sin(2.0 * np.pi * x[0]))
        )

    return f


def _oracle_ms():
    def f(x):
        return 800000.0 * (1.0 + 0.3 * x[0] / 0.7)

    return f


def _oracle_compare(case_name, direction, field_strength):
    case = CASES[case_name]
    domain = _oracle_box_mesh()
    S3 = fem.functionspace(domain, ("Lagrange", 1, (3,)))
    DG = fem.functionspace(domain, ("DG", 0))
    m = Field(S3, _oracle_m(), name="m")
    Ms = Field(DG, _oracle_ms(), name="Ms")

    demag = ThinFilmDemag(direction=direction, field_strength=field_strength)
    demag.setup(m, Ms, unit_length=1e-9)
    E = demag.compute_energy()
    H = demag.compute_field().reshape(-1, 3)
    coords = S3.tabulate_dof_coordinates()
    order = np.lexsort((coords[:, 2], coords[:, 1], coords[:, 0]))
    coords_s, H_s = coords[order], H[order]

    ref_coords = np.asarray(case["coordinates"]["values"])
    energy_q = _scalar_quantity(case, "energy")
    H_q = _quantity(case, "H_vertex")
    m_q = _quantity(case, "m_vertex")

    assert coords_s.shape == ref_coords.shape
    np.testing.assert_allclose(coords_s, ref_coords, rtol=0, atol=1e-9)

    m_coords, m_values = m.coords_and_values()
    m_order = np.lexsort((m_coords[:, 2], m_coords[:, 1], m_coords[:, 0]))
    np.testing.assert_allclose(
        m_values[m_order], np.asarray(m_q["values"]),
        atol=m_q["tolerances"]["absolute"], rtol=m_q["tolerances"]["relative"])

    e_tol = energy_q["tolerances"]
    np.testing.assert_allclose(
        float(E), energy_q["value"], atol=e_tol["absolute"], rtol=e_tol["relative"])
    H_tol = H_q["tolerances"]
    np.testing.assert_allclose(
        H_s, np.asarray(H_q["values"]), atol=H_tol["absolute"],
        rtol=H_tol["relative"])


def test_oracle_varying_ms_default_strength():
    _oracle_compare("varying_ms_default_strength", "z", None)


def test_oracle_explicit_strength_x_direction():
    _oracle_compare("explicit_strength_x_direction", "x", 5.0e5)


# --------------------------------------------------------------------------
# Simulation integration (legacy never wired ThinFilmDemag into sim_with;
# it is only ever added directly, exactly as ported here)
# --------------------------------------------------------------------------

def test_thin_film_demag_added_to_simulation_directly():
    box = mesh.create_box(
        MPI.COMM_WORLD, [(0.0, 0.0, 0.0), (5.0, 5.0, 5.0)], [2, 2, 2],
        mesh.CellType.tetrahedron)
    sim = Simulation(box, Ms_CONST, unit_length=1e-9, name="thin_film_demag_direct")
    sim.set_m((0.0, 0.0, 1.0))
    sim.add(ThinFilmDemag())
    assert sim.has_interaction("ThinFilmDemag")
    assert sim.total_energy() == pytest.approx(0.0, abs=1e-25)
    interaction = sim.get_interaction("ThinFilmDemag")
    H = interaction.compute_field().reshape((-1, 3))
    expected = np.zeros_like(H)
    expected[:, 2] = -Ms_CONST
    np.testing.assert_allclose(H, expected, rtol=1e-12)
