conf = {'nameshort': 'basics',
        'names': ('Finmag Users',),
        'tutorials' : ['tutorial-using-ipython-notebook',
                       'tutorial-example2',
                       'tutorial-saving-averages-demo',
                       'tutorial-scheduling-events',
                       'tutorial-relaxations-of-a-single-nanodisk',
                       'tutorial-coupled-relaxation-of-two-nanodisks',
                       #'tutorial-running-simulations-with-dmi',
                       'tutorial-sampling-m-at-arbitrary-positions',
                       'ref-restarting-simulations',
                       'tutorial-use-of-logging',
                       'ref-using-timings',
                       ]}
