* <2012-02-01 Wed 17:02>

Skype chat with Gabriel.

Suggested that he should start with computation of the demag field, following Andreas Thesis. 

Explained physical role of demagnetisation field.

Initially (before we meet in Southampton next week) to look at simplified computation where space is meshed outside the magnetic body, and we use Dirichlet boundary conditions at the boundary of the meshed region.

Suggest to use a region that is about 5 times as large as the central magnetic body.

Suggest to start with spherical magnetic body and uniform magnetisation in sphere as the result is analytically known. An example is in the nmag manual at http://nmag.soton.ac.uk/nmag/0.2/manual/html/example1/doc.html

Andreas thesis is in shared Dropbox/finmag folder, relevant section is 2.2.

Hopefully, this is a task that is sufficiently simple to start from, yet of great importance for the whole project.

Plan to review who is doing what when we get together next week.

* <2012-02-02 Thu> Discussion with Marijan about Individual Research Project

Will attempt to find Skyrmion state (ignoring demagnetisation fields initially). Will need to find and implement Dzyaloshinsky-Moriya term, and use together with LLG time integration and exchange (and maybe anisotropy or applied field) exchange.

* <2012-02-02 Thu> Discussion with Weiwei about Individual Research Project

Will attempt to implement the Baryakhter (B) damping term, and study its effect on dynamics (spin wave dynamics, spectra, dispersion relation?) in comparison to conventional damping term.

The B damping term is likely to introduce a new (pico second?) time scale into the problem. Efficient time integration (using CVODE, say) will be crucial.

